"""Author the lightweight sky-ambience models from the approved reference sheet.

This is the img2threejs source of truth for the distant plane and bird. The
runtime factory is generated; do not edit it by hand.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent
FACTORY = ROOT / "components" / "game" / "models" / "createSkyAmbienceModel.ts"
SPEC = HERE / "ambience-sculpt-spec.json"


SPEC_DATA = {
    "schemaVersion": 1,
    "asset": "environment-ambience",
    "referenceImage": "plane-birds-reference.png",
    "intake": {
        "source": "ChatGPT image generation, 2026-07-30",
        "purpose": "distant non-interactable sky dressing",
        "recognitionCues": [
            "rounded cream propeller plane with coral nose and blue wings",
            "small rounded bird with two broad readable wing poses",
        ],
    },
    "runtimeContract": {
        "colliders": False,
        "castsShadows": False,
        "cameraRelative": True,
        "lowCost": True,
        "interactive": False,
    },
    "stages": {
        "intake": "complete",
        "blockout": "complete",
        "structural": "complete",
        "materials": "complete",
        "runtime": "generated",
    },
    "reviewHistory": [
        {
            "date": "2026-07-30",
            "pass": "fast-mode structural eyeball",
            "status": "skipped-formal-review",
            "note": "Reference silhouettes were reduced for distant readability; no formal img2threejs scoring review was performed.",
        }
    ],
}


FACTORY_SOURCE = r'''// GENERATED by assets/reference/environment-ambience/author_ambience_spec.py
// Source reference: assets/reference/environment-ambience/plane-birds-reference.png
// Decorative only: no colliders, shadows, raycast affordances, or gameplay state.
import * as THREE from "three";

function material(color: string, roughness = 0.78): THREE.MeshStandardMaterial {
  return new THREE.MeshStandardMaterial({ color, roughness, metalness: 0 });
}

function mesh(
  name: string,
  geometry: THREE.BufferGeometry,
  surface: THREE.Material,
  position: [number, number, number],
  rotation: [number, number, number] = [0, 0, 0],
): THREE.Mesh {
  const value = new THREE.Mesh(geometry, surface);
  value.name = name;
  value.position.set(...position);
  value.rotation.set(...rotation);
  value.castShadow = false;
  value.receiveShadow = false;
  value.raycast = () => undefined;
  return value;
}

export function createSkyPlaneModel(): THREE.Group {
  const root = new THREE.Group();
  root.name = "sky-plane";
  const cream = material("#fff0c7");
  const coral = material("#ff6f61", 0.66);
  const blue = material("#4ba8e8", 0.7);
  const ink = material("#173354", 0.5);
  const silver = material("#e8eef4", 0.42);

  root.add(mesh("fuselage", new THREE.CapsuleGeometry(0.34, 1.75, 5, 10), cream, [0, 0, 0], [0, 0, -Math.PI / 2]));
  root.add(mesh("nose", new THREE.SphereGeometry(0.39, 12, 8), coral, [1.05, 0, 0]));
  root.add(mesh("main-wing", new THREE.BoxGeometry(1.05, 0.1, 2.7), blue, [-0.02, -0.02, 0]));
  root.add(mesh("tail-wing", new THREE.BoxGeometry(0.55, 0.07, 1.25), blue, [-1.08, 0.02, 0]));
  root.add(mesh("tail-fin", new THREE.ConeGeometry(0.42, 0.76, 3), blue, [-1.04, 0.44, 0], [0, 0, -0.16]));
  root.add(mesh("windscreen", new THREE.BoxGeometry(0.38, 0.34, 0.7), ink, [0.54, 0.18, 0]));
  for (const x of [0.05, -0.33, -0.7]) {
    root.add(mesh(`window-${x}`, new THREE.BoxGeometry(0.2, 0.2, 0.72), ink, [x, 0.24, 0]));
  }
  const propeller = new THREE.Group();
  propeller.name = "propeller__pivot";
  propeller.position.set(1.45, 0, 0);
  propeller.add(mesh("propeller-a", new THREE.CapsuleGeometry(0.075, 0.74, 3, 6), silver, [0, 0, 0], [0, 0, 0]));
  propeller.add(mesh("propeller-b", new THREE.CapsuleGeometry(0.075, 0.74, 3, 6), silver, [0, 0, 0], [Math.PI / 2, 0, 0]));
  propeller.rotation.z = Math.PI / 4;
  root.add(propeller);
  root.scale.setScalar(0.72);
  return root;
}

export function createSkyBirdModel(): THREE.Group {
  const root = new THREE.Group();
  root.name = "sky-bird";
  const cream = material("#fff1c9");
  const blue = material("#3c91cf", 0.72);
  const gold = material("#e7a72f", 0.7);
  const ink = material("#142b49", 0.5);
  root.add(mesh("body", new THREE.SphereGeometry(0.23, 9, 7), cream, [0, 0, 0]));
  root.add(mesh("beak", new THREE.ConeGeometry(0.07, 0.18, 4), gold, [0.25, 0.01, 0], [0, 0, -Math.PI / 2]));
  root.add(mesh("eye-left", new THREE.SphereGeometry(0.025, 6, 4), ink, [0.18, 0.08, 0.11]));
  root.add(mesh("eye-right", new THREE.SphereGeometry(0.025, 6, 4), ink, [0.18, 0.08, -0.11]));
  const left = new THREE.Group();
  left.name = "wing-left__pivot";
  left.position.set(-0.03, 0.04, 0.16);
  left.add(mesh("wing-left", new THREE.ConeGeometry(0.2, 0.72, 3), blue, [0, 0, 0.3], [Math.PI / 2, 0, 0]));
  const right = new THREE.Group();
  right.name = "wing-right__pivot";
  right.position.set(-0.03, 0.04, -0.16);
  right.add(mesh("wing-right", new THREE.ConeGeometry(0.2, 0.72, 3), blue, [0, 0, -0.3], [-Math.PI / 2, 0, 0]));
  root.add(left, right);
  return root;
}
'''


def main() -> None:
    SPEC.write_text(json.dumps(SPEC_DATA, indent=2) + "\n", encoding="utf-8")
    FACTORY.write_text(FACTORY_SOURCE, encoding="utf-8")
    print(f"wrote {SPEC.relative_to(ROOT)}")
    print(f"wrote {FACTORY.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
