import { getBrowserSupabase } from "@/lib/supabase/browser";
import { challengeSchema, displayNameSchema } from "@/lib/game/schemas";
import type { AttemptFinishResult, AttemptStartResult, ChallengeDTO, CreateShareInput, CreateShareResult, FinishAttemptInput, GuestProfile, PublishChildInput, PublishChildResult, RecordShareOpenInput, StartAttemptInput } from "@/lib/game/types";
import type { GameRepository } from "./Repository";
import { customMapBrowseResponseSchema, customMapDetailSchema, type CustomMapBrowseInput, type CustomMapBrowseResponse, type CustomMapDetail, type CustomMapEventType, type CustomMapMetadataInput, type CustomMapPublishInput, type CustomMapReportReason } from "@/lib/game/community-maps";

export class SupabaseRepository implements GameRepository{readonly mode="supabase" as const;private async token():Promise<string>{const supabase=getBrowserSupabase();let{data:{session}}=await supabase.auth.getSession();if(!session){const result=await supabase.auth.signInAnonymously();if(result.error||!result.data.session)throw new Error("Anonymous sign-in is unavailable.");session=result.data.session;}return session.access_token;}private async request<T>(url:string,init:RequestInit={}):Promise<T>{const token=await this.token();const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`,...init.headers},cache:"no-store"});const body:unknown=await response.json();if(!response.ok)throw new Error(typeof body==="object"&&body!==null&&"error" in body?JSON.stringify((body as {error:unknown}).error):"Request failed");return body as T;}
async ensureGuest():Promise<GuestProfile>{return this.request("/api/profile");}async updateProfile(displayName:string):Promise<GuestProfile>{return this.request("/api/profile",{method:"POST",body:JSON.stringify({displayName:displayNameSchema.parse(displayName)})});}async listTrending(limit=6):Promise<ChallengeDTO[]>{const data=await this.request<unknown[]>(`/api/chains?limit=${limit}`);return data.map((item)=>challengeSchema.parse(item));}async getChallenge(slug:string):Promise<ChallengeDTO>{return challengeSchema.parse(await this.request(`/api/challenges/${encodeURIComponent(slug)}`));}async listCustomMaps(input:CustomMapBrowseInput={}):Promise<CustomMapBrowseResponse>{const query=new URLSearchParams();if(input.q)query.set("q",input.q);if(input.sort)query.set("sort",input.sort);if(input.limit)query.set("limit",String(input.limit));if(input.cursor)query.set("cursor",input.cursor);if(input.mine)query.set("mine","1");return customMapBrowseResponseSchema.parse(await this.request(`/api/maps?${query}`));}async getCustomMap(mapId:string,versionId?:string):Promise<CustomMapDetail>{return customMapDetailSchema.parse(await this.request(`/api/maps/${encodeURIComponent(mapId)}${versionId?`?version=${encodeURIComponent(versionId)}`:""}`));}async publishCustomMap(input:CustomMapPublishInput):Promise<CustomMapDetail>{return customMapDetailSchema.parse(await this.request("/api/maps",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify(input)}));}async updateCustomMap(mapId:string,input:CustomMapMetadataInput):Promise<CustomMapDetail>{return customMapDetailSchema.parse(await this.request(`/api/maps/${encodeURIComponent(mapId)}`,{method:"PATCH",body:JSON.stringify(input)}));}async rollbackCustomMap(mapId:string,versionId:string):Promise<CustomMapDetail>{return customMapDetailSchema.parse(await this.request(`/api/maps/${encodeURIComponent(mapId)}/rollback`,{method:"POST",body:JSON.stringify({versionId})}));}async recordCustomMapEvent(mapId:string,versionId:string,type:CustomMapEventType):Promise<boolean>{const result=await this.request<{recorded:boolean}>(`/api/maps/${encodeURIComponent(mapId)}/events`,{method:"POST",body:JSON.stringify({versionId,type})});return result.recorded;}async reportCustomMap(mapId:string,versionId:string,reason:CustomMapReportReason,note=""):Promise<boolean>{const result=await this.request<{recorded:boolean}>(`/api/maps/${encodeURIComponent(mapId)}/reports`,{method:"POST",body:JSON.stringify({versionId,reason,note})});return result.recorded;}async moderateCustomMap(mapId:string,status:"active"|"quarantined"|"rejected",versionId?:string,note=""):Promise<CustomMapDetail>{return customMapDetailSchema.parse(await this.request(`/api/maps/${encodeURIComponent(mapId)}/moderation`,{method:"POST",body:JSON.stringify({status,versionId,note})}));}async createRootChain(track?:readonly string[]):Promise<ChallengeDTO>{
  // The track HAS to travel. This took no argument while the interface
  // declared one, so a picked map or an editor course type-checked and was
  // silently dropped on this path - the button worked on the demo repository
  // and rolled the dice in production. Body present only when a course was
  // actually composed; the server treats absence as the classic track.
  return challengeSchema.parse(await this.request("/api/chains",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},...(track&&track.length>0?{body:JSON.stringify({track})}:{})}));}async startAttempt(input:StartAttemptInput):Promise<AttemptStartResult>{return this.request("/api/attempts/start",{method:"POST",headers:{"Idempotency-Key":input.idempotencyKey},body:JSON.stringify(input)});}async finishAttempt(input:FinishAttemptInput):Promise<AttemptFinishResult>{return this.request("/api/attempts/finish",{method:"POST",headers:{"Idempotency-Key":input.idempotencyKey},body:JSON.stringify(input)});}async publishChild(input:PublishChildInput):Promise<PublishChildResult>{return this.request("/api/challenges/publish-child",{method:"POST",headers:{"Idempotency-Key":input.idempotencyKey},body:JSON.stringify(input)});}async createShare(input:CreateShareInput):Promise<CreateShareResult>{return this.request("/api/shares",{method:"POST",headers:{"Idempotency-Key":input.idempotencyKey},body:JSON.stringify(input)});}async recordShareOpen(input:RecordShareOpenInput):Promise<void>{await this.request("/api/shares/open",{method:"POST",body:JSON.stringify(input)});}}
