"""Author the first reference-led wearable rebuild wave.

This is the deterministic author source.  The generated TypeScript is runtime
output and must not be edited by hand.  New forms are based on the source images
listed in wearable-upgrade-spec.json, including the generated missing-item sheet.
"""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent

SPEC = {
    "pipeline": "img2threejs reference -> measured socket blockout -> generated runtime factory",
    "revision": "aaa-wave-1-tank-unburied",
    "referenceSheet": "assets/reference/wearable-upgrades/missing-wearables-reference.png",
    "sourceReferences": [
        "assets/reference/wear-tank.png",
        "assets/reference/wear-puffer.png",
        "assets/reference/wear-vest.png",
        "assets/reference/wear-sandal.png",
        "assets/reference/wear-cape.png",
        "assets/reference/wear-wings.png",
        "assets/reference/wearable-upgrades/missing-wearables-reference.png",
    ],
    "items": ["tank", "puffer", "vest", "barefoot", "sandal", "kilt", "bedroll", "cape", "wings", "flag", "balloon"],
    "fitBasis": "runner sockets and clearance constants in createWardrobeModels.ts",
    "features": {
        "tank": ["torso profile", "open armholes", "neck and arm binding"],
        "puffer": ["split padded panels", "zip track, teeth and pull", "sleeve-safe armholes"],
        "vest": ["split padded panels", "deep shaped armholes", "zip track, teeth and pull"],
        "barefoot": [
            "single continuous asymmetric foot volume",
            "tapered ankle and instep bridge",
            "heel-to-toe silhouette rather than an oval capsule",
        ],
        "sandal": ["fitted shaped bed", "cross straps", "heel sling"],
        "kilt": ["front, side and rear pleat rhythm", "flared hem"],
        "bedroll": ["carrier frame", "compression straps", "buckles and tie bridge"],
        "cape": ["thick curved panels", "folds", "scalloped hem", "neck yoke and clasps"],
        "wings": ["thick membranes", "perimeter frame", "veins", "back mounting plate"],
        "flag": ["waved thick cloth", "asymmetric swallow tail", "separate pole, seam and finial"],
        "balloon": ["compact rotation-safe reach", "knot, tether and wrist retention loop"],
    },
    "reviewStatus": "aaa wave 1: fast-mode eyeball review, front and side per item against the 4173 preview; wardrobe suite green; no formal ledger review",
}

SOURCE = r'''// GENERATED by assets/reference/wearable-upgrades/author_wearable_upgrades.py
// Reference manifest: assets/reference/wearable-upgrades/wearable-upgrade-spec.json
import * as THREE from "three";

export type WearableUpgradeId = "tank" | "puffer" | "vest" | "barefoot" | "sandal" | "kilt" | "bedroll" | "cape" | "wings" | "flag" | "balloon";
type Tint = "main" | "trim" | "cream" | "skin" | "knit" | "rubber" | "plastic" | "metal" | "glass";

const placeholder = new THREE.MeshStandardMaterial({ color: 0xffffff, side: THREE.DoubleSide });
function mesh(geometry: THREE.BufferGeometry, tint: Tint, name: string, position: [number, number, number] = [0, 0, 0]) {
  const value = new THREE.Mesh(geometry, placeholder);
  value.name = `upgrade:${name}`;
  value.position.set(...position);
  value.userData["wardrobeTint"] = tint;
  value.castShadow = true;
  value.receiveShadow = true;
  value.raycast = () => undefined;
  return value;
}
function ball(x: number, y: number, z: number) {
  const geometry = new THREE.SphereGeometry(1, 20, 14);
  geometry.scale(x, y, z);
  return geometry;
}
function box(x: number, y: number, z: number, bevel = 0.012) {
  const shape = new THREE.Shape();
  const hx = x / 2, hy = y / 2, r = Math.min(bevel, hx, hy);
  shape.moveTo(-hx + r, -hy); shape.lineTo(hx - r, -hy); shape.quadraticCurveTo(hx, -hy, hx, -hy + r);
  shape.lineTo(hx, hy - r); shape.quadraticCurveTo(hx, hy, hx - r, hy); shape.lineTo(-hx + r, hy);
  shape.quadraticCurveTo(-hx, hy, -hx, hy - r); shape.lineTo(-hx, -hy + r); shape.quadraticCurveTo(-hx, -hy, -hx + r, -hy);
  const geometry = new THREE.ExtrudeGeometry(shape, { depth: z, bevelEnabled: true, bevelSize: r * 0.45, bevelThickness: r * 0.45, bevelSegments: 2, curveSegments: 5 });
  geometry.translate(0, 0, -z / 2);
  return geometry;
}
function add(root: THREE.Group, ...parts: THREE.Object3D[]) { root.add(...parts); }
function pathTube(points: readonly [number, number, number][], radius: number, tint: Tint, name: string, closed = false) {
  const curve = new THREE.CatmullRomCurve3(points.map(([x, y, z]) => new THREE.Vector3(x, y, z)), closed, "centripetal");
  return mesh(new THREE.TubeGeometry(curve, Math.max(10, points.length * 5), radius, 7, closed), tint, name);
}
function thickShape(points: readonly [number, number][], depth = 0.018) {
  const shape = new THREE.Shape();
  shape.moveTo(points[0]![0], points[0]![1]);
  for (const point of points.slice(1)) shape.lineTo(point[0], point[1]);
  shape.closePath();
  const geometry = new THREE.ExtrudeGeometry(shape, {
    depth,
    bevelEnabled: true,
    bevelSize: Math.min(0.006, depth * 0.3),
    bevelThickness: Math.min(0.004, depth * 0.22),
    bevelSegments: 2,
    curveSegments: 8,
  });
  geometry.translate(0, 0, -depth / 2);
  return geometry;
}
function footLast() {
  // A small anatomical last lofted from heel to toe. Each station has its own
  // width and vertical profile, which gives the bare foot a raised instep,
  // planted sole, broad forefoot and tapered toe instead of a flat extruded
  // puck. The back stations sink into the ankle bridge below.
  const stations = [
    { z: -0.145, width: 0.064, bottom: -0.052, top: 0.06 },
    { z: -0.085, width: 0.078, bottom: -0.058, top: 0.122 },
    { z: 0.0, width: 0.09, bottom: -0.06, top: 0.158 },
    { z: 0.105, width: 0.108, bottom: -0.055, top: 0.112 },
    { z: 0.185, width: 0.094, bottom: -0.047, top: 0.078 },
    { z: 0.225, width: 0.052, bottom: -0.032, top: 0.045 },
  ] as const;
  const radialSegments = 12;
  const positions: number[] = [];
  for (const station of stations) {
    const cy = (station.top + station.bottom) / 2;
    const ry = (station.top - station.bottom) / 2;
    for (let index = 0; index < radialSegments; index += 1) {
      const angle = (index / radialSegments) * Math.PI * 2;
      positions.push(
        Math.cos(angle) * station.width,
        cy + Math.sin(angle) * ry,
        station.z,
      );
    }
  }
  const indices: number[] = [];
  for (let station = 0; station < stations.length - 1; station += 1) {
    const here = station * radialSegments;
    const next = (station + 1) * radialSegments;
    for (let index = 0; index < radialSegments; index += 1) {
      const after = (index + 1) % radialSegments;
      indices.push(here + index, next + after, next + index);
      indices.push(here + index, here + after, next + after);
    }
  }
  const heelCenter = positions.length / 3;
  positions.push(0, 0.004, stations[0]!.z);
  const toeCenter = positions.length / 3;
  positions.push(0, 0.006, stations[stations.length - 1]!.z);
  for (let index = 0; index < radialSegments; index += 1) {
    const after = (index + 1) % radialSegments;
    indices.push(heelCenter, after, index);
    const toeStart = (stations.length - 1) * radialSegments;
    indices.push(toeCenter, toeStart + index, toeStart + after);
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();
  return geometry;
}
function wavedShape(points: readonly [number, number][], depth = 0.018, amplitude = 0.02) {
  const contour = points.map(([x, y]) => new THREE.Vector2(x, y));
  const triangles = THREE.ShapeUtils.triangulateShape(contour, []);
  const xs = points.map(([x]) => x);
  const minX = Math.min(...xs), span = Math.max(0.001, Math.max(...xs) - minX);
  const positions: number[] = [];
  for (const side of [-1, 1] as const)
    for (const [x, y] of points) {
      const phase = ((x - minX) / span) * Math.PI * 1.7;
      positions.push(x, y, Math.sin(phase) * amplitude + side * depth / 2);
    }
  const count = points.length;
  const indices: number[] = [];
  for (const triangle of triangles) {
    const a = triangle[0]!, b = triangle[1]!, c = triangle[2]!;
    indices.push(a, b, c, count + c, count + b, count + a);
  }
  for (let index = 0; index < count; index += 1) {
    const next = (index + 1) % count;
    indices.push(index, next, count + next, index, count + next, count + index);
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();
  return geometry;
}
function ring(radius: number, tube: number, tint: Tint, name: string, y: number, zScale = 0.8) {
  const value = mesh(new THREE.TorusGeometry(radius, tube, 7, 24), tint, name, [0, y, 0]);
  value.rotation.x = Math.PI / 2;
  value.scale.z = zScale;
  return value;
}

function tank(root: THREE.Group) {
  // A continuous knit shell follows the runner from waist to neck. The previous
  // profile was authored against the tank's own silhouette rather than the
  // torso lathe underneath it, and between the chest and the neck it dipped
  // UNDER the body surface (0.254 at a height where the torso itself reaches
  // 0.262), so the runner swallowed the garment and only the two bindings
  // survived on camera. Every station below is the measured torso radius at
  // that height plus a constant 0.016 stand-off, which is how the tee's
  // torsoShell(0.014) stays visible, plus a little for the knit's weight.
  const profile = [
    new THREE.Vector2(0.242, -0.175),
    new THREE.Vector2(0.257, -0.12),
    new THREE.Vector2(0.275, -0.06),
    new THREE.Vector2(0.278, -0.023),
    new THREE.Vector2(0.275, 0.03),
    new THREE.Vector2(0.265, 0.084),
    new THREE.Vector2(0.255, 0.138),
    new THREE.Vector2(0.244, 0.191),
    new THREE.Vector2(0.228, 0.245),
    new THREE.Vector2(0.206, 0.285),
    new THREE.Vector2(0.199, 0.292),
  ];
  const lower = mesh(new THREE.LatheGeometry(profile, 28), "main", "tank-profile-shell");
  lower.scale.z = 0.8;
  add(root, lower, ring(0.246, 0.013, "knit", "tank-hem-binding", -0.164, 0.8));
  const neck = ring(0.199, 0.014, "knit", "tank-neck-binding", 0.292, 0.8);
  neck.userData["wardrobeNoOutline"] = true;
  add(root, neck);
  // Short shoulder seams make the tank construction legible without fake
  // panels floating beyond the runner's front and back planes. They sit on the
  // rebuilt shell's own surface: radius 0.2075 at their height, 45 degrees
  // round, with the z leg scaled by the shell's own 0.8.
  for (const side of [-1, 1] as const) {
    const seam = pathTube([
      [side * 0.145, 0.282, 0.118], [side * 0.202, 0.29, 0],
      [side * 0.145, 0.282, -0.118],
    ], 0.012, "knit", `tank-shoulder-seam-${side}`);
    seam.userData["wardrobeNoOutline"] = true;
    add(root, seam);
  }
}

function quilted(root: THREE.Group, vest: boolean) {
  const prefix = vest ? "vest" : "puffer";
  // One softly inflated shell carries shallow horizontal quilt ribs. The old
  // split front/back/side pad for every row gave every baffle its own ink
  // outline, turning the garment into a stack of black tires at picker scale.
  const shell = mesh(new THREE.CylinderGeometry(0.246, 0.272, 0.44, 28, 4, true), "main", `${prefix}-under-shell`, [0, 0.045, 0]);
  shell.scale.z = vest ? 0.79 : 0.84;
  add(root, shell);
  const baffleYs = [-0.125, -0.045, 0.035, 0.115, 0.195];
  for (const [index, y] of baffleYs.entries()) {
    const radius = 0.268 - index * 0.003;
    const rib = ring(radius, 0.006, "main", `${prefix}-baffle-rib-${index}`, y, vest ? 0.79 : 0.84);
    rib.userData["wardrobeNoOutline"] = true;
    add(root, rib);
  }

  // Raised zipper tape, individual teeth, stop boxes and a readable pull.
  const zipZ = 0.274;
  add(root, mesh(box(0.052, 0.432, 0.018, 0.008), "trim", `${prefix}-zip-tape`, [0, 0.045, zipZ]));
  for (let index = 0; index < 11; index += 1) {
    const y = -0.145 + index * 0.038;
    for (const side of [-1, 1] as const)
      add(root, mesh(box(0.012, 0.019, 0.026, 0.004), "metal", `${prefix}-zip-tooth-${index}-${side}`, [side * 0.009, y, zipZ + 0.013]));
  }
  const slider = mesh(box(0.046, 0.055, 0.032, 0.01), "metal", `${prefix}-zip-slider`, [0, 0.19, zipZ + 0.025]);
  const pull = mesh(new THREE.TorusGeometry(0.022, 0.006, 6, 14), "metal", `${prefix}-zip-pull`, [0, 0.225, zipZ + 0.03]);
  add(root, slider, pull);

  if (vest) {
    // Proud piping traces the open side of each armhole. There is no torso pad
    // behind these curves, so the negative space is real from front and side.
    for (const side of [-1, 1] as const)
      add(root, pathTube([
        [side * 0.23, 0.08, 0.17], [side * 0.255, 0.14, 0.105],
        [side * 0.255, 0.225, 0], [side * 0.225, 0.285, -0.11],
      ], 0.011, "knit", `vest-armhole-binding-${side}`));
  }
}

function barefoot(root: THREE.Group) {
  const foot = mesh(footLast(), "skin", "bare-foot", [0, 0.008, 0.02]);

  // The shoe socket is the ankle. A tapered bridge rises through the bottom
  // of the calf and sinks into the heel/instep below, so there is no daylight
  // between leg and foot during heel strike, toe-off or the victory pose.
  const ankle = mesh(
    new THREE.CylinderGeometry(0.076, 0.09, 0.23, 18, 3),
    "skin",
    "bare-foot-ankle-bridge",
    [0, 0.11, -0.06],
  );
  ankle.scale.z = 0.82;
  ankle.userData["wardrobeNoOutline"] = true;
  add(root, foot, ankle);
}

function sandal(root: THREE.Group) {
  const footOutline: readonly [number, number][] = [
    [-0.062, -0.12], [0.062, -0.12], [0.084, -0.055], [0.094, 0.055],
    [0.086, 0.145], [0.058, 0.185], [-0.058, 0.185], [-0.086, 0.145],
    [-0.094, 0.055], [-0.084, -0.055],
  ];
  const bedOutline: readonly [number, number][] = footOutline.map(([x, z]) => [x * 1.08, z + (z > 0.14 ? 0.012 : -0.004)] as [number, number]);
  const bed = mesh(thickShape(bedOutline, 0.034), "rubber", "sandal-fitted-bed", [0, -0.052, 0.018]);
  bed.rotation.x = Math.PI / 2;
  const foot = mesh(thickShape(footOutline, 0.09), "skin", "sandal-shaped-foot", [0, 0.006, 0.02]);
  foot.rotation.x = Math.PI / 2;
  add(root, bed, foot);

  // Curved tubes hug the instep instead of hovering as flat diagonal planks.
  for (const side of [-1, 1] as const)
    add(root, pathTube([
      [side * 0.082, 0.035, -0.002], [side * 0.052, 0.072, 0.045],
      [0, 0.085, 0.085], [-side * 0.052, 0.072, 0.125],
    ], 0.018, "main", `sandal-cross-strap-${side}`));
  add(root, pathTube([
    [-0.073, 0.026, -0.072], [-0.085, 0.07, -0.105], [0, 0.092, -0.13],
    [0.085, 0.07, -0.105], [0.073, 0.026, -0.072],
  ], 0.014, "main", "sandal-heel-sling"));
}

function kilt(root: THREE.Group) {
  // CylinderGeometry takes top radius first. The old order made the kilt taper
  // inward toward its hem; the wider second radius gives it the expected flare.
  const skirt = mesh(new THREE.CylinderGeometry(0.205, 0.245, 0.29, 24, 3, true), "main", "kilt-skirt", [0, -0.02, 0]);
  skirt.scale.z = 0.78;
  add(root, skirt, ring(0.205, 0.018, "knit", "kilt-waist", 0.125, 0.78));
  // Pleats wrap through both profiles and the rear, so turning the runner no
  // longer turns a detailed front into a smooth lampshade.
  const pleatCount = 12;
  for (let index = 0; index < pleatCount; index += 1) {
    const angle = (index / pleatCount) * Math.PI * 2;
    const radius = 0.222;
    const pleat = mesh(
      box(0.008, 0.225, 0.012, 0.003),
      index % 3 === 0 ? "trim" : "main",
      `kilt-pleat-${index}`,
      [Math.sin(angle) * radius, -0.01, Math.cos(angle) * radius * 0.78],
    );
    pleat.rotation.y = angle;
    pleat.rotation.z = Math.sin(angle) * 0.035;
    pleat.userData["wardrobeNoOutline"] = true;
    add(root, pleat);
  }
  add(root, ring(0.238, 0.009, "knit", "kilt-rolled-hem", -0.165, 0.78));
}

function bedroll(root: THREE.Group) {
  const roll = mesh(new THREE.CylinderGeometry(0.11, 0.11, 0.5, 20), "main", "bedroll-body", [0, 0.09, -0.29]);
  roll.rotation.z = Math.PI / 2;
  add(root, roll);
  for (const side of [-1, 1]) {
    const end = mesh(new THREE.TorusGeometry(0.075, 0.018, 7, 20, Math.PI * 1.8), "trim", `bedroll-spiral-${side}`, [side * 0.254, 0.09, -0.29]);
    end.rotation.y = Math.PI / 2;
    add(root, end);
  }
  for (const x of [-0.145, 0.145]) {
    const strap = mesh(new THREE.TorusGeometry(0.117, 0.014, 6, 18), "knit", `bedroll-strap-${x}`, [x, 0.09, -0.29]);
    strap.rotation.z = Math.PI / 2;
    add(root, strap);
    const buckle = mesh(box(0.042, 0.052, 0.018, 0.008), "metal", `bedroll-buckle-${x}`, [x, 0.19, -0.2]);
    add(root, buckle);
  }
  // A rigid carrier keeps the roll attached to the back instead of floating as
  // an isolated cylinder. Short tie loops visually connect roll, frame and rig.
  for (const x of [-0.215, 0.215])
    add(root, mesh(box(0.026, 0.30, 0.028, 0.008), "metal", `bedroll-frame-rail-${x}`, [x, 0.075, -0.215]));
  add(root,
    mesh(box(0.45, 0.026, 0.028, 0.008), "metal", "bedroll-frame-top", [0, 0.22, -0.215]),
    mesh(box(0.45, 0.026, 0.028, 0.008), "metal", "bedroll-frame-bottom", [0, -0.07, -0.215]),
    pathTube([[-0.16, -0.055, -0.202], [-0.12, -0.115, -0.225], [0, -0.135, -0.245], [0.12, -0.115, -0.225], [0.16, -0.055, -0.202]], 0.009, "knit", "bedroll-carrier-tie"),
  );
}

function cape(root: THREE.Group) {
  root.position.y = 0.02;
  root.scale.set(1.08, 1.04, 1);
  // Three overlapping thick panels bow around the back. The side panels sit
  // forward and turn toward the ribs; the centre panel sits furthest back,
  // producing curvature and real overlap instead of one paper-thin plane.
  const centre = mesh(thickShape([
    [-0.17, 0.27], [0.17, 0.27], [0.235, -0.13], [0.15, -0.17],
    [0.055, -0.145], [-0.055, -0.175], [-0.15, -0.145], [-0.235, -0.17],
  ], 0.026), "main", "cape-centre-panel", [0, 0, -0.278]);
  add(root, centre);
  for (const side of [-1, 1] as const) {
    const panel = mesh(thickShape([
      [0, 0.245], [side * 0.17, 0.255], [side * 0.39, -0.115],
      [side * 0.345, -0.17], [side * 0.255, -0.145], [side * 0.18, -0.175],
      [side * 0.105, -0.14],
    ], 0.024), "main", `cape-side-panel-${side}`, [0, 0, -0.245]);
    panel.rotation.y = side * 0.08;
    add(root, panel);
    add(root, pathTube([
      [side * 0.075, 0.245, -0.267], [side * 0.12, 0.11, -0.285],
      [side * 0.17, -0.02, -0.292], [side * 0.22, -0.145, -0.27],
    ], 0.011, "trim", `cape-raised-fold-${side}`));
  }
  add(root, pathTube([
    [-0.385, -0.13, -0.235], [-0.345, -0.17, -0.245], [-0.255, -0.145, -0.264],
    [-0.18, -0.175, -0.278], [-0.055, -0.175, -0.292], [0.055, -0.145, -0.292],
    [0.18, -0.175, -0.278], [0.255, -0.145, -0.264], [0.345, -0.17, -0.245], [0.385, -0.13, -0.235],
  ], 0.012, "knit", "cape-scalloped-hem"));

  // The yoke and dual mount tabs explain how the cape stays on the runner.
  add(root,
    pathTube([[-0.18, 0.245, -0.225], [-0.09, 0.292, -0.205], [0, 0.275, -0.198], [0.09, 0.292, -0.205], [0.18, 0.245, -0.225]], 0.022, "knit", "cape-neck-yoke"),
    mesh(box(0.055, 0.085, 0.032, 0.012), "plastic", "cape-mount-left", [-0.105, 0.245, -0.194]),
    mesh(box(0.055, 0.085, 0.032, 0.012), "plastic", "cape-mount-right", [0.105, 0.245, -0.194]),
    mesh(new THREE.TorusGeometry(0.034, 0.011, 7, 18), "cream", "cape-clasp", [0, 0.273, -0.186]),
  );
}

function wings(root: THREE.Group) {
  root.scale.set(1.08, 1.1, 1);
  const outline: readonly [number, number][] = [[0.035, 0.09], [0.14, 0.32], [0.29, 0.40], [0.39, 0.30], [0.32, 0.15], [0.40, 0.09], [0.32, 0.01], [0.28, -0.11], [0.17, -0.07], [0.07, -0.02]];
  for (const side of [-1, 1] as const) {
    const points = outline.map(([x, y]) => [x * side, y] as [number, number]);
    const panel = mesh(thickShape(points, 0.024), "main", `wing-thick-membrane-${side}`, [0, 0, -0.255]);
    add(root, panel);
    add(root, pathTube(points.map(([x, y]) => [x, y, -0.238] as [number, number, number]), 0.012, "cream", `wing-perimeter-frame-${side}`, true));
    const rootPoint: [number, number, number] = [side * 0.055, 0.075, -0.232];
    for (const [index, target] of ([
      [side * 0.29, 0.37, -0.232],
      [side * 0.34, 0.17, -0.232],
      [side * 0.31, 0.015, -0.232],
      [side * 0.25, -0.08, -0.232],
    ] as const).entries())
      add(root, pathTube([rootPoint, [side * 0.16, (rootPoint[1] + target[1]) * 0.55, -0.225], [target[0], target[1], target[2]]], 0.009, "cream", `wing-vein-${side}-${index}`));
  }
  add(root,
    mesh(box(0.15, 0.20, 0.042, 0.025), "plastic", "wing-back-mount", [0, 0.08, -0.205]),
    pathTube([[-0.11, 0.17, -0.188], [0, 0.21, -0.178], [0.11, 0.17, -0.188]], 0.014, "metal", "wing-upper-brace"),
    pathTube([[-0.11, -0.005, -0.188], [0, -0.035, -0.178], [0.11, -0.005, -0.188]], 0.014, "metal", "wing-lower-brace"),
    mesh(ball(0.052, 0.06, 0.034), "cream", "wing-centre-knot", [0, 0.075, -0.226]),
  );
}

function flag(root: THREE.Group) {
  // The authored presentation tilt leans tall props toward the skull. A small
  // whole-prop outboard bias keeps the finial and waving tip clear in victory.
  root.position.x = 0.015;
  const pole = mesh(new THREE.CylinderGeometry(0.013, 0.013, 0.48, 10), "metal", "flag-pole", [0.05, 0.11, 0]);
  const clothPoints: readonly [number, number][] = [
    [0, 0.13], [0.08, 0.145], [0.165, 0.12], [0.225, 0.085],
    [0.172, -0.005], [0.235, -0.105], [0.15, -0.07], [0.065, -0.09], [0, -0.075],
  ];
  const cloth = mesh(wavedShape(clothPoints, 0.022, 0.026), "main", "flag-waved-swallowtail", [0.052, 0.22, 0.012]);
  // The invariant ink outline is a back-face shell of the same geometry, and
  // for a waved 0.022u sheet the enlarged shell's far side shows IN FRONT of
  // the cloth wherever the wave bends away - photographed, the whole flag
  // read as ink. The seam and piping give the cloth its edges instead.
  cloth.userData["wardrobeNoOutline"] = true;
  const seam = mesh(box(0.021, 0.225, 0.022, 0.007), "knit", "flag-reinforced-seam", [0.064, 0.245, 0.01]);
  const finial = mesh(ball(0.018, 0.018, 0.018), "plastic", "flag-finial", [0.068, 0.365, 0]);
  const grip = mesh(new THREE.CylinderGeometry(0.016, 0.016, 0.105, 10), "rubber", "flag-grip", [0.068, -0.055, 0]);
  add(root, pole, cloth, seam, finial, grip,
    pathTube([[0.062, 0.347, 0.02], [0.13, 0.36, 0.036], [0.21, 0.325, 0.02], [0.275, 0.305, 0.005]], 0.008, "knit", "flag-top-piping"),
  );
}

function balloon(root: THREE.Group) {
  // The string starts in the palm and bows outward before reaching the
  // balloon. Keeping the balloon above the hand but outside the head's
  // silhouette makes it visibly held without covering the runner's face.
  const balloon = mesh(ball(0.075, 0.105, 0.085), "main", "balloon-body", [0.20, 0.39, -0.06]);
  const knot = mesh(new THREE.ConeGeometry(0.022, 0.038, 8), "main", "balloon-knot", [0.20, 0.267, -0.06]);
  knot.rotation.z = Math.PI;
  const curve = new THREE.CatmullRomCurve3([
    new THREE.Vector3(0.048, 0.01, 0),
    new THREE.Vector3(0.085, 0.105, -0.018),
    new THREE.Vector3(0.145, 0.19, -0.045),
    new THREE.Vector3(0.20, 0.267, -0.06),
  ]);
  const string = mesh(new THREE.TubeGeometry(curve, 20, 0.005, 6, false), "trim", "balloon-string");
  const retention = mesh(new THREE.TorusGeometry(0.035, 0.008, 6, 18), "rubber", "balloon-retention-loop", [0.045, -0.005, 0]);
  retention.rotation.x = Math.PI / 2;
  const highlight = mesh(ball(0.018, 0.034, 0.009), "glass", "balloon-highlight", [0.175, 0.425, 0.017]);
  highlight.rotation.z = -0.35;
  add(root, balloon, knot, string, retention, highlight);
}

export function createWearableUpgradeModel(id: WearableUpgradeId): THREE.Group {
  const root = new THREE.Group();
  root.name = `wearable-upgrade:${id}`;
  switch (id) {
    case "tank": tank(root); break;
    case "puffer": quilted(root, false); break;
    case "vest": quilted(root, true); break;
    case "barefoot": barefoot(root); break;
    case "sandal": sandal(root); break;
    case "kilt": kilt(root); break;
    case "bedroll": bedroll(root); break;
    case "cape": cape(root); break;
    case "wings": wings(root); break;
    case "flag": flag(root); break;
    case "balloon": balloon(root); break;
  }
  return root;
}
'''


def main() -> None:
    (HERE / "wearable-upgrade-spec.json").write_text(json.dumps(SPEC, indent=2) + "\n", encoding="utf-8")
    target = ROOT / "components" / "game" / "models" / "createWearableUpgradeModels.ts"
    target.write_text(SOURCE, encoding="utf-8")
    print(f"wrote {HERE / 'wearable-upgrade-spec.json'}")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
