"""Author the first reference-led wearable rebuild wave.

This is the deterministic author source.  The generated TypeScript is runtime
output and must not be edited by hand.  New forms are based on the source images
listed in wearable-upgrade-spec.json, including the generated missing-item sheet.
"""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent

SPEC = {
    "pipeline": "img2threejs reference -> measured socket blockout -> generated runtime factory",
    "referenceSheet": "assets/reference/wearable-upgrades/missing-wearables-reference.png",
    "sourceReferences": [
        "assets/reference/wear-tank.png",
        "assets/reference/wear-puffer.png",
        "assets/reference/wear-vest.png",
        "assets/reference/wear-sandal.png",
        "assets/reference/wear-cape.png",
        "assets/reference/wear-wings.png",
        "assets/reference/wearable-upgrades/missing-wearables-reference.png",
    ],
    "items": ["tank", "puffer", "vest", "barefoot", "sandal", "kilt", "bedroll", "cape", "wings", "flag", "balloon"],
    "fitBasis": "runner sockets and clearance constants in createWardrobeModels.ts",
    "reviewStatus": "generated structural pass; multi-angle runtime review required",
}

SOURCE = r'''// GENERATED by assets/reference/wearable-upgrades/author_wearable_upgrades.py
// Reference manifest: assets/reference/wearable-upgrades/wearable-upgrade-spec.json
import * as THREE from "three";

export type WearableUpgradeId = "tank" | "puffer" | "vest" | "barefoot" | "sandal" | "kilt" | "bedroll" | "cape" | "wings" | "flag" | "balloon";
type Tint = "main" | "trim" | "cream" | "skin";

const placeholder = new THREE.MeshStandardMaterial({ color: 0xffffff, side: THREE.DoubleSide });
function mesh(geometry: THREE.BufferGeometry, tint: Tint, name: string, position: [number, number, number] = [0, 0, 0]) {
  const value = new THREE.Mesh(geometry, placeholder);
  value.name = `upgrade:${name}`;
  value.position.set(...position);
  value.userData["wardrobeTint"] = tint;
  value.castShadow = true;
  value.receiveShadow = true;
  value.raycast = () => undefined;
  return value;
}
function ball(x: number, y: number, z: number) {
  const geometry = new THREE.SphereGeometry(1, 20, 14);
  geometry.scale(x, y, z);
  return geometry;
}
function box(x: number, y: number, z: number, bevel = 0.012) {
  const shape = new THREE.Shape();
  const hx = x / 2, hy = y / 2, r = Math.min(bevel, hx, hy);
  shape.moveTo(-hx + r, -hy); shape.lineTo(hx - r, -hy); shape.quadraticCurveTo(hx, -hy, hx, -hy + r);
  shape.lineTo(hx, hy - r); shape.quadraticCurveTo(hx, hy, hx - r, hy); shape.lineTo(-hx + r, hy);
  shape.quadraticCurveTo(-hx, hy, -hx, hy - r); shape.lineTo(-hx, -hy + r); shape.quadraticCurveTo(-hx, -hy, -hx + r, -hy);
  const geometry = new THREE.ExtrudeGeometry(shape, { depth: z, bevelEnabled: true, bevelSize: r * 0.45, bevelThickness: r * 0.45, bevelSegments: 2, curveSegments: 5 });
  geometry.translate(0, 0, -z / 2);
  return geometry;
}
function add(root: THREE.Group, ...parts: THREE.Object3D[]) { root.add(...parts); }
function ring(radius: number, tube: number, tint: Tint, name: string, y: number, zScale = 0.8) {
  const value = mesh(new THREE.TorusGeometry(radius, tube, 7, 24), tint, name, [0, y, 0]);
  value.rotation.x = Math.PI / 2;
  value.scale.z = zScale;
  return value;
}

function tank(root: THREE.Group) {
  // Lower shell plus separate shoulder straps leaves a real scoop neck and
  // cut armholes instead of closing the garment with a generic sleeve cap.
  const lower = mesh(new THREE.CylinderGeometry(0.235, 0.265, 0.30, 24, 2, true), "main", "tank-lower", [0, -0.028, 0]);
  lower.scale.z = 0.8;
  const back = mesh(box(0.39, 0.22, 0.035, 0.025), "main", "tank-back", [0, 0.205, -0.205]);
  for (const side of [-1, 1]) {
    const strap = mesh(box(0.085, 0.235, 0.055, 0.025), "main", `tank-strap-${side}`, [side * 0.155, 0.205, 0.17]);
    strap.rotation.z = -side * 0.08;
    const binding = mesh(box(0.022, 0.23, 0.061, 0.01), "cream", `tank-binding-${side}`, [side * 0.112, 0.202, 0.173]);
    binding.rotation.z = -side * 0.18;
    add(root, strap, binding);
  }
  add(root, lower, back, ring(0.248, 0.014, "cream", "tank-hem", -0.164));
}

function quilted(root: THREE.Group, vest: boolean) {
  // A continuous under-shell prevents the old open gaps between baffles.
  const shell = mesh(new THREE.CylinderGeometry(0.255, 0.285, 0.49, 24, 5, true), "main", vest ? "vest-shell" : "puffer-shell", [0, 0.069, 0]);
  shell.scale.z = vest ? 0.82 : 0.86;
  add(root, shell);
  for (const [index, y] of [-0.13, -0.035, 0.06, 0.155, 0.25].entries()) {
    if (vest && index === 4) continue;
    // Fine piping reads as stitched baffles without turning the torso into a
    // stack of detached hoops at gameplay scale.
    add(root, ring(0.270 - index * 0.005, 0.0045, "trim", `${vest ? "vest" : "puffer"}-seam-${index}`, y, vest ? 0.82 : 0.86));
  }
  const zipper = mesh(box(0.028, 0.455, 0.03, 0.008), "trim", `${vest ? "vest" : "puffer"}-zip`, [0, 0.06, 0.235]);
  add(root, zipper);
}

function barefoot(root: THREE.Group) {
  // The stock sneaker is a rectangular shoe even with its sole hidden. A
  // rounded foot gives Footwear: None an actual unclothed anatomy silhouette.
  const foot = mesh(ball(0.105, 0.07, 0.17), "skin", "bare-foot", [0, 0.015, 0.035]);
  const toe = mesh(ball(0.098, 0.055, 0.09), "skin", "bare-toes", [0, 0.002, 0.145]);
  add(root, foot, toe);
}

function sandal(root: THREE.Group) {
  // Keep the sole inside the bare-foot silhouette. The former rectangular
  // footbed was wide and long enough to read as a floating snowboard in the
  // wardrobe preview, especially when both feet were side by side.
  const foot = mesh(ball(0.092, 0.062, 0.155), "skin", "sandal-foot", [0, 0.014, 0.035]);
  const bed = mesh(box(0.178, 0.025, 0.285, 0.024), "cream", "sandal-footbed", [0, -0.052, 0.035]);
  const heel = mesh(box(0.17, 0.025, 0.095, 0.018), "trim", "sandal-heel", [0, -0.066, -0.06]);
  add(root, foot, bed, heel);
  for (const side of [-1, 1]) {
    const strap = mesh(box(0.042, 0.025, 0.145, 0.012), "main", `sandal-cross-${side}`, [side * 0.027, 0.058, 0.058]);
    strap.rotation.y = side * 0.55;
    add(root, strap);
  }
  const sling = mesh(new THREE.TorusGeometry(0.082, 0.013, 6, 18, Math.PI), "main", "sandal-sling", [0, 0.052, -0.075]);
  sling.rotation.x = Math.PI / 2;
  add(root, sling);
}

function kilt(root: THREE.Group) {
  const skirt = mesh(new THREE.CylinderGeometry(0.275, 0.205, 0.255, 24, 3, true), "main", "kilt-skirt", [0, -0.0025, 0]);
  skirt.scale.z = 0.78;
  add(root, skirt, ring(0.205, 0.018, "trim", "kilt-waist", 0.125, 0.78));
  for (let index = 0; index < 8; index += 1) {
    const x = -0.19 + index * 0.054;
    const pleat = mesh(box(0.014, 0.205, 0.018, 0.006), index % 2 ? "trim" : "main", `kilt-pleat-${index}`, [x, -0.01, 0.208]);
    pleat.rotation.z = (index - 3.5) * 0.02;
    add(root, pleat);
  }
}

function bedroll(root: THREE.Group) {
  const roll = mesh(new THREE.CylinderGeometry(0.105, 0.105, 0.38, 20), "main", "bedroll-body", [0, 0.09, -0.29]);
  roll.rotation.z = Math.PI / 2;
  add(root, roll);
  for (const side of [-1, 1]) {
    const end = mesh(new THREE.TorusGeometry(0.072, 0.018, 7, 20, Math.PI * 1.8), "trim", `bedroll-spiral-${side}`, [side * 0.194, 0.09, -0.29]);
    end.rotation.y = Math.PI / 2;
    add(root, end);
  }
  for (const x of [-0.105, 0.105]) {
    const strap = mesh(new THREE.TorusGeometry(0.112, 0.014, 6, 18), "cream", `bedroll-strap-${x}`, [x, 0.09, -0.29]);
    strap.rotation.z = Math.PI / 2;
    add(root, strap);
  }
}

function clothShape(points: readonly [number, number][]) {
  const shape = new THREE.Shape();
  shape.moveTo(points[0]![0], points[0]![1]);
  for (const point of points.slice(1)) shape.lineTo(point[0], point[1]);
  shape.closePath();
  return new THREE.ShapeGeometry(shape, 10);
}
function cape(root: THREE.Group) {
  root.position.y = 0.005;
  const cloth = mesh(clothShape([[-0.16, 0.27], [0.16, 0.27], [0.34, -0.15], [0.19, -0.18], [0.06, -0.15], [-0.06, -0.18], [-0.19, -0.15], [-0.34, -0.17]]), "main", "cape-cloth", [0, 0, -0.25]);
  const foldLeft = mesh(box(0.018, 0.40, 0.02, 0.006), "trim", "cape-fold-left", [-0.12, 0.03, -0.263]);
  const foldRight = foldLeft.clone(); foldRight.name = "upgrade:cape-fold-right"; foldRight.position.x = 0.12;
  const clasp = mesh(new THREE.TorusGeometry(0.035, 0.012, 7, 18), "cream", "cape-clasp", [0, 0.27, -0.265]);
  add(root, cloth, foldLeft, foldRight, clasp);
}

function wings(root: THREE.Group) {
  const outline: readonly [number, number][] = [[0.035, 0.09], [0.14, 0.32], [0.29, 0.40], [0.39, 0.30], [0.32, 0.15], [0.40, 0.09], [0.32, 0.01], [0.28, -0.11], [0.17, -0.07], [0.07, -0.02]];
  for (const side of [-1, 1]) {
    const points = outline.map(([x, y]) => [x * side, y] as [number, number]);
    const panel = mesh(clothShape(points), "main", `wing-panel-${side}`, [0, 0, -0.255]);
    add(root, panel);
    const feathers = [
      [0.18, 0.18, 0.19, -0.44],
      [0.27, 0.11, 0.17, -0.66],
      [0.21, 0.02, 0.13, -0.38],
    ] as const;
    for (const [index, [x, y, length, angle]] of feathers.entries()) {
      const feather = mesh(ball(0.062, length, 0.022), "main", `wing-feather-${side}-${index}`, [side * x, y, -0.268]);
      feather.rotation.z = side * angle;
      add(root, feather);
    }
    const spar = mesh(box(0.014, 0.29, 0.014, 0.005), "cream", `wing-spar-${side}`, [side * 0.11, 0.11, -0.274]);
    spar.rotation.z = side * -0.32;
    add(root, spar);
  }
  add(root, mesh(ball(0.045, 0.055, 0.028), "cream", "wing-knot", [0, 0.075, -0.27]));
}

function flag(root: THREE.Group) {
  const pole = mesh(new THREE.CylinderGeometry(0.013, 0.013, 0.38, 10), "trim", "flag-pole", [0.05, 0.1, 0]);
  const cloth = mesh(clothShape([[0, 0.13], [0.22, 0.115], [0.205, 0], [0.235, -0.105], [0, -0.09]]), "main", "flag-cloth", [0.052, 0.23, 0.012]);
  const seam = mesh(box(0.018, 0.235, 0.014, 0.006), "cream", "flag-seam", [0.064, 0.242, 0]);
  add(root, pole, cloth, seam);
}

function balloon(root: THREE.Group) {
  // The string starts in the palm and bows outward before reaching the
  // balloon. Keeping the balloon above the hand but outside the head's
  // silhouette makes it visibly held without covering the runner's face.
  const balloon = mesh(ball(0.068, 0.10, 0.082), "main", "balloon-body", [0.31, 0.48, -0.12]);
  const knot = mesh(new THREE.ConeGeometry(0.02, 0.036, 8), "trim", "balloon-knot", [0.31, 0.365, -0.12]);
  knot.rotation.z = Math.PI;
  const curve = new THREE.CatmullRomCurve3([
    new THREE.Vector3(0.048, 0.01, 0),
    new THREE.Vector3(0.11, 0.13, -0.04),
    new THREE.Vector3(0.21, 0.24, -0.08),
    new THREE.Vector3(0.31, 0.365, -0.12),
  ]);
  const string = mesh(new THREE.TubeGeometry(curve, 20, 0.006, 6, false), "trim", "balloon-string");
  add(root, balloon, knot, string);
}

export function createWearableUpgradeModel(id: WearableUpgradeId): THREE.Group {
  const root = new THREE.Group();
  root.name = `wearable-upgrade:${id}`;
  switch (id) {
    case "tank": tank(root); break;
    case "puffer": quilted(root, false); break;
    case "vest": quilted(root, true); break;
    case "barefoot": barefoot(root); break;
    case "sandal": sandal(root); break;
    case "kilt": kilt(root); break;
    case "bedroll": bedroll(root); break;
    case "cape": cape(root); break;
    case "wings": wings(root); break;
    case "flag": flag(root); break;
    case "balloon": balloon(root); break;
  }
  return root;
}
'''


def main() -> None:
    (HERE / "wearable-upgrade-spec.json").write_text(json.dumps(SPEC, indent=2) + "\n", encoding="utf-8")
    target = ROOT / "components" / "game" / "models" / "createWearableUpgradeModels.ts"
    target.write_text(SOURCE, encoding="utf-8")
    print(f"wrote {HERE / 'wearable-upgrade-spec.json'}")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
