// GENERATED by assets/reference/headwear-upgrades/author_headwear_upgrades.py
// Reference manifest: assets/reference/headwear-upgrades/headwear-upgrade-spec.json
import * as THREE from "three";

export type HeadwearUpgradeId = "helmet" | "crown" | "cowboy" | "beret" | "grin" | "beard" | "mask" | "goggles" | "aviator" | "visorband";
type Tint = "main" | "trim" | "ink" | "cream" | "steel" | "glow" | "glass";

const placeholder = new THREE.MeshStandardMaterial({ color: 0xffffff, side: THREE.DoubleSide });
function mesh(geometry: THREE.BufferGeometry, tint: Tint, name: string, position: [number, number, number] = [0, 0, 0]) {
  const value = new THREE.Mesh(geometry, placeholder);
  value.name = `head-upgrade:${name}`;
  value.position.set(...position);
  value.userData["wardrobeTint"] = tint;
  value.castShadow = true;
  value.receiveShadow = true;
  value.raycast = () => undefined;
  return value;
}
function add(root: THREE.Group, ...parts: THREE.Object3D[]) { root.add(...parts); }
function ball(x: number, y: number, z: number, width = 22, height = 14) {
  const geometry = new THREE.SphereGeometry(1, width, height);
  geometry.scale(x, y, z);
  return geometry;
}
function box(x: number, y: number, z: number, bevel = 0.01) {
  const shape = new THREE.Shape();
  const hx = x / 2, hy = y / 2, r = Math.min(bevel, hx, hy);
  shape.moveTo(-hx + r, -hy); shape.lineTo(hx - r, -hy); shape.quadraticCurveTo(hx, -hy, hx, -hy + r);
  shape.lineTo(hx, hy - r); shape.quadraticCurveTo(hx, hy, hx - r, hy); shape.lineTo(-hx + r, hy);
  shape.quadraticCurveTo(-hx, hy, -hx, hy - r); shape.lineTo(-hx, -hy + r); shape.quadraticCurveTo(-hx, -hy, -hx + r, -hy);
  const geometry = new THREE.ExtrudeGeometry(shape, { depth: z, bevelEnabled: true, bevelSize: r * 0.45, bevelThickness: r * 0.45, bevelSegments: 2, curveSegments: 5 });
  geometry.translate(0, 0, -z / 2);
  return geometry;
}
function shape(points: readonly (readonly [number, number])[], depth = 0.018) {
  const outline = new THREE.Shape();
  outline.moveTo(points[0]![0], points[0]![1]);
  for (const [x, y] of points.slice(1)) outline.lineTo(x, y);
  outline.closePath();
  const geometry = new THREE.ExtrudeGeometry(outline, { depth, bevelEnabled: true, bevelSize: 0.006, bevelThickness: 0.004, bevelSegments: 2 });
  geometry.translate(0, 0, -depth / 2);
  return geometry;
}
function curved(geometry: THREE.BufferGeometry, halfWidth: number, crown: number) {
  const position = geometry.getAttribute("position") as THREE.BufferAttribute;
  for (let index = 0; index < position.count; index += 1) {
    const x = position.getX(index);
    const normalized = Math.min(1, Math.abs(x) / halfWidth);
    position.setZ(index, position.getZ(index) + crown * (1 - normalized * normalized));
  }
  position.needsUpdate = true;
  geometry.computeVertexNormals();
  return geometry;
}
function curvedShape(points: readonly (readonly [number, number])[], depth = 0.018, crown = 0.03) {
  const halfWidth = Math.max(...points.map(([x]) => Math.abs(x)));
  return curved(shape(points, depth), halfWidth, crown);
}
function frameShape(
  outer: readonly (readonly [number, number])[],
  inner: readonly (readonly [number, number])[],
  depth = 0.018,
  crown = 0.025,
) {
  const outline = new THREE.Shape();
  outline.moveTo(outer[0]![0], outer[0]![1]);
  for (const [x, y] of outer.slice(1)) outline.lineTo(x, y);
  outline.closePath();
  const opening = new THREE.Path();
  const reversed = [...inner].reverse();
  opening.moveTo(reversed[0]![0], reversed[0]![1]);
  for (const [x, y] of reversed.slice(1)) opening.lineTo(x, y);
  opening.closePath();
  outline.holes.push(opening);
  const geometry = new THREE.ExtrudeGeometry(outline, {
    depth,
    bevelEnabled: true,
    bevelSize: 0.005,
    bevelThickness: 0.003,
    bevelSegments: 2,
    curveSegments: 8,
  });
  geometry.translate(0, 0, -depth / 2);
  const halfWidth = Math.max(...outer.map(([x]) => Math.abs(x)));
  return curved(geometry, halfWidth, crown);
}
function line(points: readonly (readonly [number, number, number])[], radius: number, segments = 24) {
  const curve = new THREE.CatmullRomCurve3(points.map(([x, y, z]) => new THREE.Vector3(x, y, z)));
  return new THREE.TubeGeometry(curve, segments, radius, 7, false);
}
function curledOvalBrim() {
  const segments = 48;
  const positions: number[] = [];
  const indices: number[] = [];
  const outerX = 0.46, outerZ = 0.355, innerX = 0.25, innerZ = 0.22, thickness = 0.022;
  for (let index = 0; index <= segments; index += 1) {
    const angle = (index / segments) * Math.PI * 2;
    const sideCurl = 0.078 + 0.105 * Math.abs(Math.cos(angle)) ** 2;
    const innerY = 0.105 + 0.025 * Math.abs(Math.cos(angle)) ** 2;
    const cos = Math.cos(angle), sin = Math.sin(angle);
    positions.push(
      cos * outerX, sideCurl + thickness / 2, sin * outerZ,
      cos * innerX, innerY + thickness / 2, sin * innerZ,
      cos * outerX, sideCurl - thickness / 2, sin * outerZ,
      cos * innerX, innerY - thickness / 2, sin * innerZ,
    );
  }
  for (let index = 0; index < segments; index += 1) {
    const at = index * 4, next = (index + 1) * 4;
    indices.push(
      at, next, at + 1, next, next + 1, at + 1,
      at + 2, at + 3, next + 2, next + 2, at + 3, next + 3,
      at, at + 2, next, next, at + 2, next + 2,
      at + 1, next + 1, at + 3, next + 1, next + 3, at + 3,
    );
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();
  return geometry;
}
function torus(radius: number, tube: number, arc = Math.PI * 2) {
  return new THREE.TorusGeometry(radius, tube, 7, Math.max(12, Math.round(arc * 7)), arc);
}

function helmet(root: THREE.Group) {
  // The cap, visor frame, cheek rails and chin guard overlap into one continuous
  // motorcycle shell. The glass sits inside the frame rather than acting as an
  // opaque plate pasted over the face.
  const shellGeometry = new THREE.SphereGeometry(1, 28, 18, 0, Math.PI * 2, 0, Math.PI * 0.61);
  shellGeometry.scale(0.386, 0.37, 0.342);
  const shell = mesh(shellGeometry, "main", "helmet-shell", [0, 0.075, 0.004]);
  const visorOuter = [[-0.305, 0.095], [-0.255, 0.13], [0.255, 0.13], [0.305, 0.095], [0.268, -0.095], [0.205, -0.125], [-0.205, -0.125], [-0.268, -0.095]] as const;
  const visorInner = [[-0.27, 0.075], [-0.23, 0.098], [0.23, 0.098], [0.27, 0.075], [0.235, -0.065], [0.185, -0.09], [-0.185, -0.09], [-0.235, -0.065]] as const;
  const visor = mesh(curvedShape(visorInner, 0.008, 0.035), "glass", "helmet-glass", [0, -0.035, 0.313]);
  const visorFrame = mesh(frameShape(visorOuter, visorInner, 0.014, 0.035), "trim", "helmet-flush-visor-frame", [0, -0.035, 0.308]);
  const cheek = (side: -1 | 1) => {
    const points = side < 0
      ? [[-0.305, 0.02], [-0.235, 0.005], [-0.205, -0.17], [-0.105, -0.235], [-0.245, -0.24], [-0.325, -0.12]] as const
      : [[0.305, 0.02], [0.235, 0.005], [0.205, -0.17], [0.105, -0.235], [0.245, -0.24], [0.325, -0.12]] as const;
    const guard = mesh(curvedShape(points, 0.043, 0.013), "main", `helmet-cheek-${side}`, [0, -0.01, 0.26]);
    guard.rotation.y = side * 0.08;
    return guard;
  };
  const chinOuter = [[-0.245, 0.015], [0.245, 0.015], [0.22, -0.13], [0.145, -0.18], [-0.145, -0.18], [-0.22, -0.13]] as const;
  const chinVent = [[-0.115, -0.02], [0.115, -0.02], [0.095, -0.105], [-0.095, -0.105]] as const;
  const chin = mesh(frameShape(chinOuter, chinVent, 0.044, 0.022), "main", "helmet-chin-guard", [0, -0.205, 0.282]);
  const lowerRim = mesh(line([[-0.205, -0.35, 0.288], [0, -0.38, 0.299], [0.205, -0.35, 0.288]], 0.015), "ink", "helmet-lower-rim");
  for (const x of [-0.075, -0.025, 0.025, 0.075]) {
    const bar = mesh(box(0.016, 0.075, 0.018, 0.005), "ink", `helmet-vent-bar-${x}`, [x, -0.272, 0.325]);
    bar.rotation.z = x * 0.6;
    add(root, bar);
  }
  for (const side of [-1, 1] as const) {
    // A low rounded hinge is buried into the shell surface. The earlier tall
    // cylinder projected as detached rectangular hardware in profile.
    const hinge = mesh(ball(0.018, 0.03, 0.021, 16, 10), "steel", `helmet-flush-hinge-${side}`, [side * 0.326, -0.025, 0.158]);
    add(root, hinge);
  }
  const crownStripe = mesh(line([[0, 0.42, -0.20], [0, 0.405, 0.02], [0, 0.31, 0.29]], 0.021), "trim", "helmet-crown-stripe");
  add(root, shell, visor, visorFrame, cheek(-1), cheek(1), chin, lowerRim, crownStripe);
}

function crown(root: THREE.Group) {
  // A closed lower band seats on the skull; eight alternating points continue
  // around the whole circumference, so rear and profile views remain a crown.
  const band = mesh(new THREE.CylinderGeometry(0.318, 0.336, 0.14, 32), "main", "crown-full-band", [0, 0.145, -0.012]);
  band.scale.z = 0.94;
  const lowerRim = mesh(torus(0.329, 0.022), "trim", "crown-lower-rim", [0, 0.074, -0.012]);
  lowerRim.rotation.x = Math.PI / 2;
  lowerRim.scale.z = 0.94;
  const upperRim = mesh(torus(0.316, 0.014), "cream", "crown-upper-rim", [0, 0.215, -0.012]);
  upperRim.rotation.x = Math.PI / 2;
  upperRim.scale.z = 0.94;
  add(root, band, lowerRim, upperRim);
  const pointCount = 8;
  for (let index = 0; index < pointCount; index += 1) {
    const angle = (index / pointCount) * Math.PI * 2;
    const isCardinal = index % 2 === 0;
    const tall = isCardinal ? 0.285 : 0.205;
    const radius = 0.296;
    const x = Math.sin(angle) * radius;
    const z = Math.cos(angle) * radius - 0.012;
    const point = mesh(shape([[-0.068, 0], [-0.034, tall * 0.48], [0, tall], [0.034, tall * 0.48], [0.068, 0]], 0.05), "main", `crown-point-${index}`, [x, 0.205, z]);
    point.rotation.y = angle;
    const pearl = mesh(ball(isCardinal ? 0.033 : 0.026, isCardinal ? 0.033 : 0.026, 0.026), "cream", `crown-pearl-${index}`, [x, 0.205 + tall, z]);
    add(root, point, pearl);
  }
  const gems = [
    [-0.205, 0.14, 0.255, "trim"],
    [-0.105, 0.148, 0.302, "glow"],
    [0, 0.15, 0.318, "trim"],
    [0.105, 0.148, 0.302, "glow"],
    [0.205, 0.14, 0.255, "trim"],
  ] as const;
  for (const [index, [x, y, z, tint]] of gems.entries()) {
    const bezel = mesh(ball(0.051, 0.062, 0.018), "cream", `crown-bezel-${index}`, [x, y, z]);
    const gem = mesh(new THREE.OctahedronGeometry(index === 2 ? 0.044 : 0.036, 0), tint, `crown-gem-${index}`, [x, y, z + 0.018]);
    gem.scale.y = 1.22;
    add(root, bezel, gem);
  }
}

function cowboy(root: THREE.Group) {
  // The brim is a closed oval annulus with raised side curls, not a single
  // left-to-right tube. Its inner edge stays seated under the crown.
  const brim = mesh(curledOvalBrim(), "main", "cowboy-complete-brim", [0, 0.03, -0.015]);
  const crown = mesh(new THREE.CylinderGeometry(0.235, 0.275, 0.23, 28), "main", "cowboy-crown", [0, 0.275, -0.025]);
  crown.scale.z = 0.86;
  // Two raised lobes and a recessed centre establish the pinched western crown
  // without painting a contrast-coloured box down its face.
  const crownLeft = mesh(ball(0.142, 0.052, 0.195), "main", "cowboy-crown-lobe-left", [-0.088, 0.392, -0.035]);
  const crownRight = mesh(ball(0.142, 0.052, 0.195), "main", "cowboy-crown-lobe-right", [0.088, 0.392, -0.035]);
  const crease = mesh(line([[0, 0.408, -0.178], [0, 0.386, -0.025], [0, 0.406, 0.132]], 0.011), "trim", "cowboy-top-crease");
  const band = mesh(torus(0.266, 0.019), "trim", "cowboy-band", [0, 0.173, -0.02]);
  band.rotation.x = Math.PI / 2;
  band.scale.z = 0.86;
  const buckle = mesh(box(0.07, 0.052, 0.018, 0.012), "steel", "cowboy-buckle", [0, 0.175, 0.223]);
  add(root, brim, crown, crownLeft, crownRight, crease, band, buckle);
}

function beret(root: THREE.Group) {
  // One offset ellipsoid forms a soft, asymmetric dome. The narrow band is
  // buried into its lower edge so the profile no longer reads as stacked discs.
  const cap = mesh(ball(0.355, 0.122, 0.315, 32, 18), "main", "beret-soft-dome", [-0.052, 0.278, -0.035]);
  cap.rotation.z = 0.12;
  cap.rotation.x = -0.035;
  const headband = mesh(torus(0.292, 0.014), "trim", "beret-headband", [0, 0.194, -0.015]);
  headband.rotation.x = Math.PI / 2;
  headband.scale.z = 0.93;
  const stalk = mesh(new THREE.CylinderGeometry(0.01, 0.016, 0.052, 10), "trim", "beret-stalk", [0.045, 0.412, -0.05]);
  stalk.rotation.z = -0.35;
  add(root, cap, headband, stalk);
}

function grin(root: THREE.Group) {
  // A compact, slightly crooked smile follows the lower face. The tooth flash
  // occupies only the upper half of the cavity instead of becoming a mouthguard.
  const mouthOuter = [[-0.09, 0.015], [-0.052, 0.032], [0.005, 0.038], [0.058, 0.032], [0.092, 0.022], [0.07, -0.025], [0.028, -0.048], [-0.008, -0.052], [-0.045, -0.042], [-0.076, -0.018]] as const;
  const mouthInner = [[-0.073, 0.008], [-0.042, 0.021], [0.004, 0.026], [0.047, 0.022], [0.074, 0.014], [0.054, -0.016], [0.023, -0.032], [-0.007, -0.036], [-0.036, -0.029], [-0.06, -0.012]] as const;
  const cavity = mesh(curvedShape(mouthInner, 0.005, 0.007), "ink", "grin-small-cavity", [0, -0.172, 0.287]);
  const lip = mesh(frameShape(mouthOuter, mouthInner, 0.007, 0.007), "ink", "grin-small-curved-lip", [0, -0.172, 0.291]);
  const toothBed = mesh(curvedShape([[-0.057, 0.011], [-0.025, 0.017], [0.008, 0.019], [0.052, 0.014], [0.045, -0.009], [0.012, -0.017], [-0.022, -0.014], [-0.05, -0.006]], 0.004, 0.006), "cream", "grin-tooth-flash", [0, -0.169, 0.296]);
  add(root, cavity, toothBed, lip);
  for (const x of [-0.022, 0.012]) {
    const separator = mesh(box(0.004, 0.026, 0.003, 0.0015), "ink", `grin-tooth-gap-${x}`, [x, -0.166, 0.304]);
    separator.rotation.z = -0.04 - x * 0.45;
    add(root, separator);
  }
}

function beard(root: THREE.Group) {
  // One shallow concave U joins the cheek and jaw silhouette while remaining
  // open above the chin. Buried rounded volumes soften the surface without
  // separating into the pointed petal/mandible ring seen in the runtime sheet.
  const outline = [
    [-0.235, -0.082], [-0.215, -0.16], [-0.19, -0.245], [-0.145, -0.315],
    [-0.075, -0.355], [0, -0.37], [0.075, -0.355], [0.145, -0.315],
    [0.19, -0.245], [0.215, -0.16], [0.235, -0.082],
    [0.175, -0.105], [0.142, -0.205], [0.09, -0.25], [0.04, -0.27],
    [0, -0.274], [-0.04, -0.27], [-0.09, -0.25], [-0.142, -0.205], [-0.175, -0.105],
  ] as const;
  const base = mesh(curvedShape(outline, 0.014, 0.03), "main", "beard-connected-jaw", [0, 0, 0.267]);
  add(root, base);
  for (const side of [-1, 1] as const) {
    const sideburn = mesh(ball(0.045, 0.095, 0.022, 20, 14), "main", `beard-sideburn-${side}`, [side * 0.225, -0.145, 0.245]);
    sideburn.rotation.z = side * 0.1;
    const cheek = mesh(ball(0.074, 0.09, 0.018, 22, 14), "main", `beard-buried-cheek-${side}`, [side * 0.155, -0.235, 0.283]);
    cheek.rotation.z = side * 0.18;
    add(root, sideburn, cheek);
  }
  const chin = mesh(ball(0.105, 0.052, 0.018, 24, 14), "main", "beard-rounded-chin", [0, -0.334, 0.287]);
  add(root, chin);
}

function mask(root: THREE.Group) {
  const outline = [[-0.185, 0.06], [-0.105, 0.087], [0, 0.095], [0.105, 0.087], [0.185, 0.06], [0.16, -0.085], [0.085, -0.13], [0, -0.142], [-0.085, -0.13], [-0.16, -0.085]] as const;
  const cover = mesh(curvedShape(outline, 0.012, 0.026), "main", "mask-soft-cover", [0, -0.15, 0.294]);
  add(root, cover);
  // Curved pleat cords follow the face instead of hovering as straight slats.
  add(root, mesh(line([[-0.142, -0.08, 0.306], [0, -0.068, 0.326], [0.142, -0.08, 0.306]], 0.005), "cream", "mask-nose-strip"));
  for (const [index, y] of [-0.142, -0.18, -0.215].entries()) {
    const pleat = mesh(line([[-0.145 + index * 0.01, y, 0.309], [0, y + 0.007, 0.329], [0.145 - index * 0.01, y, 0.309]], 0.0035), "trim", `mask-pleat-${index}`);
    add(root, pleat);
  }
  for (const side of [-1, 1] as const) {
    const edge = mesh(line([[side * 0.182, -0.095, 0.299], [side * 0.17, -0.165, 0.305], [side * 0.15, -0.235, 0.299]], 0.005), "trim", `mask-edge-${side}`);
    add(root, edge);
  }
  // Separate upper and lower straps converge on the ear rather than looping
  // behind the head and returning as a rigid triangular cage.
  for (const side of [-1, 1] as const) {
    const ear = [side * 0.305, -0.145, 0.045] as const;
    const upper = mesh(line([[side * 0.18, -0.095, 0.299], [side * 0.255, -0.11, 0.175], ear], 0.0045), "cream", `mask-upper-strap-${side}`);
    const lower = mesh(line([[side * 0.15, -0.235, 0.299], [side * 0.245, -0.19, 0.15], ear], 0.0045), "cream", `mask-lower-strap-${side}`);
    add(root, upper, lower);
  }
}

function goggles(root: THREE.Group) {
  const outer = [[-0.235, 0.078], [-0.17, 0.102], [0.17, 0.102], [0.235, 0.078], [0.215, -0.063], [0.145, -0.092], [0.04, -0.086], [0, -0.045], [-0.04, -0.086], [-0.145, -0.092], [-0.215, -0.063]] as const;
  const window = [[-0.211, 0.059], [-0.155, 0.079], [0.155, 0.079], [0.211, 0.059], [0.19, -0.045], [0.132, -0.066], [0.034, -0.061], [0, -0.022], [-0.034, -0.061], [-0.132, -0.066], [-0.19, -0.045]] as const;
  const lens = mesh(curvedShape(window, 0.008, 0.027), "glass", "ski-goggle-unified-lens", [0, -0.072, 0.307]);
  const rim = mesh(frameShape(outer, window, 0.015, 0.027), "main", "ski-goggle-soft-rim", [0, -0.072, 0.304]);
  const strap = mesh(torus(0.337, 0.019), "trim", "ski-goggle-strap", [0, -0.066, -0.012]);
  strap.rotation.x = Math.PI / 2;
  strap.scale.z = 0.98;
  add(root, strap, lens, rim);
  for (const side of [-1, 1] as const) {
    const buckle = mesh(box(0.032, 0.056, 0.018, 0.008), "steel", `ski-goggle-buckle-${side}`, [side * 0.3, -0.068, 0.185]);
    buckle.rotation.y = side * 0.32;
    add(root, buckle);
  }
}

function aviator(root: THREE.Group) {
  const rimOuter = [[-0.09, 0.068], [0.09, 0.068], [0.092, 0.018], [0.065, -0.064], [0.024, -0.108], [0, -0.12], [-0.024, -0.108], [-0.065, -0.064], [-0.092, 0.018]] as const;
  const lensShape = [[-0.073, 0.051], [0.073, 0.051], [0.075, 0.015], [0.052, -0.052], [0.018, -0.09], [0, -0.101], [-0.018, -0.09], [-0.052, -0.052], [-0.075, 0.015]] as const;
  for (const side of [-1, 1] as const) {
    const lens = mesh(curvedShape(lensShape, 0.007, 0.01), "glass", `aviator-glass-${side}`, [side * 0.108, -0.076, 0.316]);
    const rim = mesh(frameShape(rimOuter, lensShape, 0.012, 0.01), "main", `aviator-teardrop-rim-${side}`, [side * 0.108, -0.076, 0.32]);
    lens.rotation.z = rim.rotation.z = -side * 0.035;
    add(root, lens, rim);
  }
  const bridge = mesh(line([[-0.027, -0.047, 0.331], [0, -0.029, 0.34], [0.027, -0.047, 0.331]], 0.007), "main", "aviator-lower-bridge");
  const brow = mesh(line([[-0.195, -0.014, 0.307], [-0.105, 0.004, 0.331], [0, 0.008, 0.34], [0.105, 0.004, 0.331], [0.195, -0.014, 0.307]], 0.006), "main", "aviator-upper-bridge");
  add(root, bridge, brow);
  for (const side of [-1, 1] as const) {
    const arm = mesh(line([[side * 0.198, -0.05, 0.314], [side * 0.255, -0.06, 0.235], [side * 0.295, -0.07, 0.13]], 0.006), "main", `aviator-temple-${side}`);
    add(root, arm);
  }
}

function visorband(root: THREE.Group) {
  const shield = [[-0.292, 0.082], [-0.22, 0.112], [0.22, 0.112], [0.292, 0.082], [0.26, -0.055], [0.14, -0.092], [0, -0.105], [-0.14, -0.092], [-0.26, -0.055]] as const;
  const lens = mesh(curvedShape(shield, 0.006, 0.038), "glass", "future-visor-thin-glass-shield", [0, -0.073, 0.307]);
  lens.renderOrder = 2;
  const brow = mesh(line([[-0.275, 0.012, 0.321], [-0.14, 0.034, 0.344], [0, 0.042, 0.354], [0.14, 0.034, 0.344], [0.275, 0.012, 0.321]], 0.006), "trim", "future-visor-brow");
  add(root, lens, brow);
  for (const side of [-1, 1] as const) {
    const temple = mesh(line([[side * 0.275, -0.072, 0.317], [side * 0.322, -0.068, 0.218], [side * 0.33, -0.075, 0.11]], 0.008), "main", `future-visor-temple-${side}`);
    const hinge = mesh(new THREE.CylinderGeometry(0.025, 0.025, 0.02, 14), "steel", `future-visor-hinge-${side}`, [side * 0.331, -0.073, 0.11]);
    hinge.rotation.z = Math.PI / 2;
    const hingeInset = mesh(new THREE.CylinderGeometry(0.011, 0.011, 0.023, 12), "trim", `future-visor-hinge-inset-${side}`, [side * 0.332, -0.073, 0.11]);
    hingeInset.rotation.z = Math.PI / 2;
    add(root, temple, hinge, hingeInset);
  }
}

export function createHeadwearUpgradeModel(id: HeadwearUpgradeId): THREE.Group {
  const root = new THREE.Group();
  root.name = `headwear-upgrade:${id}`;
  switch (id) {
    case "helmet": helmet(root); break;
    case "crown": crown(root); break;
    case "cowboy": cowboy(root); break;
    case "beret": beret(root); break;
    case "grin": grin(root); break;
    case "beard": beard(root); break;
    case "mask": mask(root); break;
    case "goggles": goggles(root); break;
    case "aviator": aviator(root); break;
    case "visorband": visorband(root); break;
  }
  return root;
}
