// GENERATED by assets/reference/hair-catalog/author_hair_catalog.py
// Source: assets/reference/hair-catalog/hair-20-style-reference.png
import * as THREE from "three";

type HairMesh = THREE.Mesh<THREE.BufferGeometry, THREE.MeshStandardMaterial>;

function surface(color: string, shade = 1): THREE.MeshStandardMaterial {
  const value = new THREE.Color(color).multiplyScalar(shade);
  const material = new THREE.MeshStandardMaterial({ color: value, roughness: 0.82, metalness: 0 });
  material.name = shade < 1 ? "hair-shadow" : "hair-main";
  return material;
}

function add(
  root: THREE.Group,
  geometry: THREE.BufferGeometry,
  material: THREE.MeshStandardMaterial,
  position: [number, number, number],
  rotation: [number, number, number] = [0, 0, 0],
  scale: [number, number, number] = [1, 1, 1],
  name = "hair-piece",
): HairMesh {
  const part = new THREE.Mesh(geometry, material);
  part.name = name;
  part.position.set(...position);
  part.rotation.set(...rotation);
  part.scale.set(...scale);
  part.castShadow = true;
  part.receiveShadow = false;
  part.raycast = () => undefined;
  part.userData["wardrobeTint"] = material.name === "hair-shadow" ? "hairShadow" : "main";
  root.add(part);
  return part;
}

const sphere = () => new THREE.SphereGeometry(1, 10, 7);
const cone = () => new THREE.ConeGeometry(1, 1, 7);
const capsule = () => new THREE.CapsuleGeometry(1, 1, 4, 8);

function cap(root: THREE.Group, main: THREE.MeshStandardMaterial, scale: [number, number, number] = [0.35, 0.24, 0.35], y = 0.12) {
  add(root, sphere(), main, [0, y, -0.015], [0, 0, 0], scale, "hair-cap");
}

function tuft(root: THREE.Group, main: THREE.MeshStandardMaterial, x: number, y: number, z: number, size = 0.1, tilt = 0) {
  add(root, cone(), main, [x, y, z], [0, 0, tilt], [size, size * 1.8, size], "hair-tuft");
}

function curl(root: THREE.Group, main: THREE.MeshStandardMaterial, x: number, y: number, z: number, size = 0.095) {
  add(root, sphere(), main, [x, y, z], [0, 0, 0], [size, size, size], "hair-curl");
}

function braid(root: THREE.Group, main: THREE.MeshStandardMaterial, x: number, z: number) {
  for (let index = 0; index < 5; index += 1) {
    const y = -0.02 - index * 0.095;
    add(root, sphere(), main, [x + Math.sin(index * 1.7) * 0.012, y, z], [0, 0, 0], [0.065, 0.078, 0.06], "hair-braid-segment");
  }
  tuft(root, main, x, -0.51, z, 0.05, Math.PI);
}

export function createHairStyleModel(id: string, color: string): THREE.Group {
  const root = new THREE.Group();
  root.name = `hair:${id}`;
  const main = surface(color);
  const shadow = surface(color, 0.62);

  switch (id) {
    case "classic":
      cap(root, main);
      // A shallow, eyebrow-safe fringe replaces the old downward cones whose
      // tips passed through both eyes and the nose.
      for (const [x, y, sx, tilt] of [
        [-0.22, 0.025, 0.105, -0.18],
        [-0.08, 0.012, 0.12, -0.06],
        [0.08, 0.012, 0.12, 0.06],
        [0.22, 0.025, 0.105, 0.18],
      ] as const) {
        add(root, sphere(), main, [x, y, 0.285], [0, 0, tilt], [sx, 0.055, 0.075], "classic-fringe");
      }
      break;
    case "buzz":
      cap(root, main, [0.337, 0.205, 0.337], 0.105);
      for (let ring = 0; ring < 3; ring += 1) for (let index = 0; index < 8; index += 1) {
        const angle = (index / 8) * Math.PI * 2 + ring * 0.25;
        curl(root, shadow, Math.sin(angle) * (0.17 + ring * 0.06), 0.16 + ring * 0.07, Math.cos(angle) * (0.17 + ring * 0.06) - 0.02, 0.025);
      }
      break;
    case "crew":
      cap(root, main, [0.34, 0.2, 0.34], 0.09);
      add(root, new THREE.CylinderGeometry(0.27, 0.31, 0.13, 12), main, [0, 0.3, -0.02], [0, 0, 0], [1, 1, 1], "crew-flat-top");
      break;
    case "spikes":
      cap(root, shadow, [0.33, 0.16, 0.33], 0.07);
      for (let index = 0; index < 12; index += 1) {
        const angle = (index / 12) * Math.PI * 2;
        tuft(root, main, Math.sin(angle) * 0.23, 0.27 + (index % 3) * 0.04, Math.cos(angle) * 0.23 - 0.02, 0.09, -Math.sin(angle) * 0.45);
      }
      tuft(root, main, 0, 0.42, -0.02, 0.11);
      break;
    case "mohawk":
      cap(root, shadow, [0.31, 0.13, 0.31], 0.04);
      for (let index = 0; index < 7; index += 1) tuft(root, main, 0, 0.26 + Math.sin(index / 6 * Math.PI) * 0.12, 0.27 - index * 0.095, 0.105);
      break;
    case "fauxhawk":
      cap(root, main, [0.34, 0.18, 0.34], 0.08);
      for (let index = 0; index < 5; index += 1) tuft(root, shadow, 0, 0.31 + Math.sin(index / 4 * Math.PI) * 0.06, 0.2 - index * 0.1, 0.07);
      break;
    case "quiff":
      cap(root, main, [0.34, 0.18, 0.34], 0.08);
      for (const [x, y, s] of [[-0.16, 0.31, 0.13], [0, 0.4, 0.16], [0.16, 0.35, 0.14]] as const)
        add(root, sphere(), main, [x, y, 0.2], [0, 0, -x], [s, s * 1.15, s * 1.35], "quiff-roll");
      break;
    case "pompadour":
      cap(root, shadow, [0.34, 0.18, 0.34], 0.08);
      for (let index = 0; index < 4; index += 1) {
        const x = -0.21 + index * 0.14;
        add(root, sphere(), main, [x, 0.39 + (index === 1 || index === 2 ? 0.05 : 0), 0.18], [0, 0, 0], [0.13, 0.17, 0.18], "pompadour-roll");
      }
      break;
    case "sidepart":
      cap(root, main);
      add(root, sphere(), main, [-0.1, 0.31, 0.08], [0, 0, 0.28], [0.28, 0.12, 0.28], "side-sweep");
      add(root, new THREE.BoxGeometry(0.012, 0.18, 0.42), shadow, [0.12, 0.25, 0.02], [0, 0, -0.42], [1, 1, 1], "side-part-line");
      break;
    case "slickback":
      cap(root, main, [0.34, 0.2, 0.36], 0.12);
      for (const x of [-0.2, -0.07, 0.07, 0.2]) add(root, capsule(), shadow, [x, 0.25, -0.05], [Math.PI / 2.2, 0, 0], [0.025, 0.13, 0.025], "slick-ridge");
      break;
    case "bob":
      cap(root, main, [0.36, 0.28, 0.36], 0.08);
      add(root, sphere(), main, [-0.29, -0.08, 0.02], [0, 0, -0.1], [0.12, 0.31, 0.25], "bob-left");
      add(root, sphere(), main, [0.29, -0.08, 0.02], [0, 0, 0.1], [0.12, 0.31, 0.25], "bob-right");
      break;
    case "curlybob":
      cap(root, shadow, [0.34, 0.22, 0.34], 0.1);
      for (const side of [-1, 1]) for (let index = 0; index < 6; index += 1) curl(root, main, side * (0.27 + (index % 2) * 0.05), 0.15 - index * 0.09, 0.12 - (index % 3) * 0.12, 0.105);
      break;
    case "afro":
      for (let yRing = 0; yRing < 3; yRing += 1) for (let index = 0; index < 10; index += 1) {
        const angle = index / 10 * Math.PI * 2;
        const radius = 0.27 + (1 - yRing) * 0.035;
        curl(root, index % 2 ? main : shadow, Math.sin(angle) * radius, 0.08 + yRing * 0.14, Math.cos(angle) * radius - 0.03, 0.13);
      }
      curl(root, main, 0, 0.48, -0.03, 0.16);
      break;
    case "puffs":
      cap(root, main, [0.34, 0.2, 0.34], 0.08);
      for (const side of [-1, 1]) {
        curl(root, shadow, side * 0.335, 0.3, -0.03, 0.12);
        for (let index = 0; index < 5; index += 1) {
          const angle = index / 5 * Math.PI * 2;
          curl(root, main, side * 0.335 + Math.sin(angle) * 0.055, 0.3 + Math.cos(angle) * 0.055, -0.03, 0.052);
        }
      }
      break;
    case "ponytail":
      cap(root, main);
      add(root, new THREE.TorusGeometry(0.075, 0.025, 6, 12), shadow, [0, 0.08, -0.35], [Math.PI / 2, 0, 0], [1, 1, 1], "pony-tie");
      add(root, capsule(), main, [0, -0.08, -0.48], [0.28, 0, 0], [0.1, 0.22, 0.1], "low-ponytail");
      break;
    case "highpony":
      cap(root, main);
      add(root, new THREE.TorusGeometry(0.075, 0.025, 6, 12), shadow, [0, 0.34, -0.25], [Math.PI / 2, 0, 0], [1, 1, 1], "pony-tie");
      for (let index = 0; index < 3; index += 1) add(root, capsule(), main, [0, 0.28 - index * 0.15, -0.4 - index * 0.07], [0.35, 0, 0], [0.105 - index * 0.012, 0.15, 0.105 - index * 0.012], "high-pony-segment");
      break;
    case "braids":
      cap(root, main, [0.34, 0.2, 0.34], 0.08);
      braid(root, main, -0.28, 0.08);
      braid(root, main, 0.28, 0.08);
      break;
    case "locs":
      cap(root, main, [0.35, 0.21, 0.35], 0.08);
      for (let index = 0; index < 10; index += 1) {
        const angle = index / 10 * Math.PI * 2;
        add(root, capsule(), index % 2 ? main : shadow, [Math.sin(angle) * 0.3, -0.08 - (index % 3) * 0.035, Math.cos(angle) * 0.24], [0, 0, Math.sin(angle) * 0.12], [0.045, 0.22 + (index % 2) * 0.05, 0.045], "loc");
      }
      break;
    case "shag":
      cap(root, main, [0.36, 0.24, 0.36], 0.08);
      for (let index = 0; index < 12; index += 1) {
        const angle = index / 12 * Math.PI * 2;
        tuft(root, index % 2 ? main : shadow, Math.sin(angle) * 0.29, -0.02 + (index % 3) * 0.07, Math.cos(angle) * 0.27 - 0.02, 0.075, -Math.sin(angle) * 0.35);
      }
      break;
    case "undercut":
      cap(root, shadow, [0.325, 0.15, 0.325], 0.04);
      add(root, sphere(), main, [-0.1, 0.32, 0.08], [0, 0, 0.32], [0.31, 0.14, 0.29], "undercut-sweep");
      for (let index = 0; index < 4; index += 1) tuft(root, main, -0.18 + index * 0.1, 0.34 + index * 0.02, 0.21 - index * 0.025, 0.075, -0.35);
      break;
    default:
      cap(root, main);
      break;
  }
  return root;
}
