// GENERATED by assets/reference/headwear-upgrades/author_headwear_upgrades.py
// Reference manifest: assets/reference/headwear-upgrades/headwear-upgrade-spec.json
import * as THREE from "three";

export type HeadwearUpgradeId = "helmet" | "crown" | "cowboy" | "beret" | "earmuffs" | "grin" | "beard" | "mask" | "goggles" | "aviator" | "visorband";
type Tint = "main" | "trim" | "ink" | "cream" | "steel" | "metal" | "glow" | "glass";

const placeholder = new THREE.MeshStandardMaterial({ color: 0xffffff, side: THREE.DoubleSide });
function mesh(geometry: THREE.BufferGeometry, tint: Tint, name: string, position: [number, number, number] = [0, 0, 0]) {
  const value = new THREE.Mesh(geometry, placeholder);
  value.name = `head-upgrade:${name}`;
  value.position.set(...position);
  value.userData["wardrobeTint"] = tint;
  value.castShadow = true;
  value.receiveShadow = true;
  value.raycast = () => undefined;
  return value;
}
function add(root: THREE.Group, ...parts: THREE.Object3D[]) { root.add(...parts); }
function ball(x: number, y: number, z: number, width = 22, height = 14) {
  const geometry = new THREE.SphereGeometry(1, width, height);
  geometry.scale(x, y, z);
  return geometry;
}
function box(x: number, y: number, z: number, bevel = 0.01) {
  const shape = new THREE.Shape();
  const hx = x / 2, hy = y / 2, r = Math.min(bevel, hx, hy);
  shape.moveTo(-hx + r, -hy); shape.lineTo(hx - r, -hy); shape.quadraticCurveTo(hx, -hy, hx, -hy + r);
  shape.lineTo(hx, hy - r); shape.quadraticCurveTo(hx, hy, hx - r, hy); shape.lineTo(-hx + r, hy);
  shape.quadraticCurveTo(-hx, hy, -hx, hy - r); shape.lineTo(-hx, -hy + r); shape.quadraticCurveTo(-hx, -hy, -hx + r, -hy);
  const geometry = new THREE.ExtrudeGeometry(shape, { depth: z, bevelEnabled: true, bevelSize: r * 0.45, bevelThickness: r * 0.45, bevelSegments: 2, curveSegments: 5 });
  geometry.translate(0, 0, -z / 2);
  return geometry;
}
function shape(points: readonly (readonly [number, number])[], depth = 0.018) {
  const outline = new THREE.Shape();
  outline.moveTo(points[0]![0], points[0]![1]);
  for (const [x, y] of points.slice(1)) outline.lineTo(x, y);
  outline.closePath();
  const geometry = new THREE.ExtrudeGeometry(outline, { depth, bevelEnabled: true, bevelSize: 0.006, bevelThickness: 0.004, bevelSegments: 2 });
  geometry.translate(0, 0, -depth / 2);
  return geometry;
}
function curved(geometry: THREE.BufferGeometry, halfWidth: number, crown: number) {
  const position = geometry.getAttribute("position") as THREE.BufferAttribute;
  for (let index = 0; index < position.count; index += 1) {
    const x = position.getX(index);
    const normalized = Math.min(1, Math.abs(x) / halfWidth);
    position.setZ(index, position.getZ(index) + crown * (1 - normalized * normalized));
  }
  position.needsUpdate = true;
  geometry.computeVertexNormals();
  return geometry;
}
function curvedShape(points: readonly (readonly [number, number])[], depth = 0.018, crown = 0.03) {
  const halfWidth = Math.max(...points.map(([x]) => Math.abs(x)));
  return curved(shape(points, depth), halfWidth, crown);
}
function frameShape(
  outer: readonly (readonly [number, number])[],
  inner: readonly (readonly [number, number])[],
  depth = 0.018,
  crown = 0.025,
) {
  const outline = new THREE.Shape();
  outline.moveTo(outer[0]![0], outer[0]![1]);
  for (const [x, y] of outer.slice(1)) outline.lineTo(x, y);
  outline.closePath();
  const opening = new THREE.Path();
  const reversed = [...inner].reverse();
  opening.moveTo(reversed[0]![0], reversed[0]![1]);
  for (const [x, y] of reversed.slice(1)) opening.lineTo(x, y);
  opening.closePath();
  outline.holes.push(opening);
  const geometry = new THREE.ExtrudeGeometry(outline, {
    depth,
    bevelEnabled: true,
    bevelSize: 0.005,
    bevelThickness: 0.003,
    bevelSegments: 2,
    curveSegments: 8,
  });
  geometry.translate(0, 0, -depth / 2);
  const halfWidth = Math.max(...outer.map(([x]) => Math.abs(x)));
  return curved(geometry, halfWidth, crown);
}
function line(points: readonly (readonly [number, number, number])[], radius: number, segments = 24) {
  const curve = new THREE.CatmullRomCurve3(points.map(([x, y, z]) => new THREE.Vector3(x, y, z)));
  return new THREE.TubeGeometry(curve, segments, radius, 7, false);
}
function curledOvalBrim() {
  const segments = 48;
  const positions: number[] = [];
  const indices: number[] = [];
  const outerX = 0.46, outerZ = 0.355, innerX = 0.25, innerZ = 0.22, thickness = 0.022;
  for (let index = 0; index <= segments; index += 1) {
    const angle = (index / segments) * Math.PI * 2;
    const sideCurl = 0.078 + 0.105 * Math.abs(Math.cos(angle)) ** 2;
    const innerY = 0.105 + 0.025 * Math.abs(Math.cos(angle)) ** 2;
    const cos = Math.cos(angle), sin = Math.sin(angle);
    positions.push(
      cos * outerX, sideCurl + thickness / 2, sin * outerZ,
      cos * innerX, innerY + thickness / 2, sin * innerZ,
      cos * outerX, sideCurl - thickness / 2, sin * outerZ,
      cos * innerX, innerY - thickness / 2, sin * innerZ,
    );
  }
  for (let index = 0; index < segments; index += 1) {
    const at = index * 4, next = (index + 1) * 4;
    indices.push(
      at, next, at + 1, next, next + 1, at + 1,
      at + 2, at + 3, next + 2, next + 2, at + 3, next + 3,
      at, at + 2, next, next, at + 2, next + 2,
      at + 1, next + 1, at + 3, next + 1, next + 3, at + 3,
    );
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();
  return geometry;
}
function torus(radius: number, tube: number, arc = Math.PI * 2) {
  return new THREE.TorusGeometry(radius, tube, 7, Math.max(12, Math.round(arc * 7)), arc);
}
function smoothstep(edge0: number, edge1: number, value: number) {
  const t = Math.min(1, Math.max(0, (value - edge0) / (edge1 - edge0)));
  return t * t * (3 - 2 * t);
}

// The runner's skull in the head socket's own frame, read off the rig rather
// than assumed: the Head mesh measures +-0.325 in x and y and +-0.310 in z
// about the socket, so it is a sphere with a shallow front-to-back squash.
const SKULL = { rx: 0.325, ry: 0.325, rz: 0.31 };

/**
 * A point on the skull pushed out along its own radii by `grow`.
 *
 * `u` is the azimuth from +Z towards +X and `v` the elevation, so y = ry sin(v).
 * Face-worn hair authored in (u, v) follows the jaw at a constant offset; the
 * flat constant-z plate it replaces stood 0.15u proud of the chin.
 */
function facePoint(u: number, v: number, grow: number): [number, number, number] {
  const flat = Math.cos(v);
  return [
    (SKULL.rx + grow) * flat * Math.sin(u),
    (SKULL.ry + grow) * Math.sin(v),
    (SKULL.rz + grow) * flat * Math.cos(u),
  ];
}

/**
 * A closed slab of hair lying on the skull between two elevation boundaries.
 *
 * The outer skin stands `swell(u, s)` above the surface and the inner skin sits
 * `bury` below it, with a rim joining them the whole way round, so the piece is
 * a solid with thickness rather than a shell with a visible back face.
 */
function facePanel(
  uMax: number,
  top: (u: number) => number,
  bottom: (u: number) => number,
  swell: (u: number, s: number) => number,
  bury = 0.006,
  uSteps = 30,
  vSteps = 14,
) {
  const rows = vSteps + 1;
  const positions: number[] = [];
  const indices: number[] = [];
  for (const skin of [0, 1]) {
    for (let i = 0; i <= uSteps; i += 1) {
      const u = -uMax + (2 * uMax * i) / uSteps;
      const from = top(u);
      const to = bottom(u);
      for (let j = 0; j < rows; j += 1) {
        const s = j / vSteps;
        const point = facePoint(u, from + (to - from) * s, skin === 0 ? swell(u, s) : -bury);
        positions.push(point[0], point[1], point[2]);
      }
    }
  }
  const inner = (uSteps + 1) * rows;
  // i runs +x and j runs downward, so (a, d, b) and (a, c, d) wind outward.
  const quad = (a: number, b: number, c: number, d: number) => {
    indices.push(a, d, b, a, c, d);
  };
  for (let i = 0; i < uSteps; i += 1) {
    for (let j = 0; j < vSteps; j += 1) {
      const at = i * rows + j;
      const next = (i + 1) * rows + j;
      quad(at, next, at + 1, next + 1);
      quad(inner + next, inner + at, inner + next + 1, inner + at + 1);
    }
  }
  for (let i = 0; i < uSteps; i += 1) {
    const at = i * rows;
    const next = (i + 1) * rows;
    quad(inner + at, inner + next, at, next);
    quad(next + vSteps, inner + next + vSteps, at + vSteps, inner + at + vSteps);
  }
  for (let j = 0; j < vSteps; j += 1) {
    quad(inner + j, j, inner + j + 1, j + 1);
    const last = uSteps * rows + j;
    quad(last, inner + last, last + 1, inner + last + 1);
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();
  return geometry;
}

// The helmet crown ellipsoid in the head socket's frame, and the half-angle of
// the face opening measured about +Z. Every helmet part is placed against these.
const HELMET_SHELL = { rx: 0.386, ry: 0.37, rz: 0.342, y: 0.075, z: 0.004 };
const HELMET_FACE = 0.78;

/**
 * The lower shell, which is a different ellipsoid from the crown on purpose.
 *
 * The crown is sized around the visor and its centre sits 0.075u high, so it
 * stops enclosing the skull below the eye line: at y -0.19 the back of the head
 * measures 1.07 of the crown's radius, i.e. 0.02u outside it. These radii are
 * chosen to pass through the crown's own bottom rim (at y -0.050 the crown's
 * section is x 0.3632, z 0.3218, and this ellipsoid's equator is exactly that),
 * so the two meet with no step, and to clear the skull by 10 to 25 per cent of
 * radius all the way down to the jaw.
 */
const HELMET_SKIRT = { rx: 0.3632, ry: 0.33, rz: 0.3218, y: -0.05, z: 0.004 };

/**
 * The surface the visor is built on, which envelopes both shells.
 *
 * The visor cannot ride either shell: the crown is the fatter of the two above
 * y -0.05 and the skirt below it, so a visor on one sinks inside the other where
 * they cross. On the front centre line this surface clears the crown by 0.008 at
 * y 0.05 and the skirt by 0.029 at y -0.156, and it stays outside the cheek pads
 * as well - the pad's widest corner measures 0.89 of this ellipsoid's radius.
 *
 * Built as sphere patches rather than as a bowed extrusion. `curved` moves
 * vertices, and an ExtrudeGeometry's face is triangulated across the whole width
 * of a bar, so a deep bow sags along every chord: measured at a 0.132 crown, the
 * middle of the frame fell 0.067 behind the shell it was meant to sit in front
 * of. A patch of the surface itself cannot do that.
 */
const HELMET_VISOR = { rx: 0.395, ry: 0.4, rz: 0.355, y: -0.02, z: 0.004 };

type HelmetShell = { rx: number; ry: number; rz: number; y: number; z: number };

/** A piece of a shell surface. THREE puts phi = PI/2 at +Z, so the face opening spans PI/2 +- HELMET_FACE. */
function helmetPatch(shell: HelmetShell, fromPhi: number, spanPhi: number, fromTheta: number, spanTheta: number, grow: number) {
  const geometry = new THREE.SphereGeometry(1, 30, 12, fromPhi, spanPhi, fromTheta, spanTheta);
  geometry.scale(shell.rx + grow, shell.ry + grow, shell.rz + grow);
  return geometry;
}

/**
 * A patch of a shell whose lower edge rises as it travels round the head.
 *
 * A SphereGeometry segment's bottom edge is a level ring, which forces the nape
 * to choose between covering the back of the skull and clearing the shoulder
 * caps: the depth that covers the centre of the nape puts the same edge out at
 * the sides, where the caps are. This builds the same surface with a bottom edge
 * that is a function of azimuth, so the back can hang low while the sides pull
 * up. Winding follows SphereGeometry's own order so it faces the same way as the
 * patches it continues.
 */
function taperedPatch(
  shell: HelmetShell,
  fromPhi: number,
  spanPhi: number,
  fromTheta: number,
  toTheta: (across: number) => number,
  steps = 30,
  rows = 6,
) {
  const positions: number[] = [];
  const indices: number[] = [];
  for (let i = 0; i <= steps; i += 1) {
    const across = i / steps;
    const phi = fromPhi + spanPhi * across;
    const bottom = toTheta(across * 2 - 1);
    for (let j = 0; j <= rows; j += 1) {
      const theta = fromTheta + (bottom - fromTheta) * (j / rows);
      positions.push(
        -shell.rx * Math.cos(phi) * Math.sin(theta),
        shell.ry * Math.cos(theta),
        shell.rz * Math.sin(phi) * Math.sin(theta),
      );
    }
  }
  for (let i = 0; i < steps; i += 1) {
    for (let j = 0; j < rows; j += 1) {
      const a = (i + 1) * (rows + 1) + j;
      const b = i * (rows + 1) + j;
      const c = i * (rows + 1) + j + 1;
      const d = (i + 1) * (rows + 1) + j + 1;
      indices.push(a, b, d, b, c, d);
    }
  }
  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute("position", new THREE.Float32BufferAttribute(positions, 3));
  geometry.setIndex(indices);
  geometry.computeVertexNormals();
  return geometry;
}

/** The height of the shell above (x, z), pushed out by `lift`. */
function helmetTop(x: number, z: number, lift: number) {
  const fx = x / HELMET_SHELL.rx;
  const fz = (z - HELMET_SHELL.z) / HELMET_SHELL.rz;
  return HELMET_SHELL.y + (HELMET_SHELL.ry + lift) * Math.sqrt(Math.max(0, 1 - fx * fx - fz * fz));
}

function helmet(root: THREE.Group) {
  // The cap, side skirt, cheek pads, visor frame and chin guard overlap into one
  // continuous motorcycle shell. Everything bolted onto the helmet is placed on
  // the shell ellipsoid itself, which is what the old crown stripe was not: its
  // rear point sat at y 0.42 against a surface at 0.372 and read as a grey
  // sliver floating off the back of the head.
  const seat: [number, number, number] = [0, HELMET_SHELL.y, HELMET_SHELL.z];
  const skirtSeat: [number, number, number] = [0, HELMET_SKIRT.y, HELMET_SKIRT.z];
  const rear = Math.PI * 1.5;
  // The crown closes over the top only as far as y 0.045, then continues as a
  // band that leaves the face opening. It used to be a full revolve down to
  // y -0.050, which put opaque shell at z 0.345 across the whole brow while the
  // visor frame reached only 0.340: the top of the visor was drawn behind the
  // shell. cos(theta) = (0.045 - 0.075) / 0.37 puts that cut at theta 0.526 PI.
  const cap = mesh(helmetPatch(HELMET_SHELL, 0, Math.PI * 2, 0, Math.PI * 0.526, 0), "main", "helmet-shell", seat);
  const crownBand = mesh(
    helmetPatch(HELMET_SHELL, Math.PI / 2 + HELMET_FACE, Math.PI * 2 - HELMET_FACE * 2, Math.PI * 0.515, Math.PI * 0.095, 0),
    "main",
    "helmet-crown-band",
    seat,
  );
  // The shell used to stop at y -0.050, so in profile it was a black skullcap
  // over a bare jaw. The skirt carries it from there down to the jaw everywhere
  // except across the face opening.
  //
  // Its lower edge is tapered rather than level, and that is the whole point of
  // the piece. `across` runs -1 to 1 from one edge of the face opening round to
  // the other, so 0 is straight back and the ears fall at 0.665. A level rim at
  // the depth the back wants, y -0.2805, passes 0.0726 from the shoulder cap at
  // (0.168, 1.14, 0) at rest, and the head's own twist closes that to 0.0020 -
  // it passed the suite, but by a fiftieth of what every other head garment
  // clears by, so any later change would have broken it. The rim now holds
  // -0.2805 at the back and at the edges of the face opening, and lifts to -0.225
  // only around the ears at 0.665, which is where the caps are. That is still
  // 0.083 below the bottom of the ear at -0.142.
  //
  // The lift is a bump on the ear rather than a step, because a step lifted the
  // rim at the front edges too, where z 0.167 already carries the rim clear of
  // the cap and the only effect was to open the jaw. Measured over the twist,
  // the bump's half width trades the two against each other: 0.34 gives 0.0355
  // of cap clearance, 0.42 gives 0.0451, 0.50 gives 0.0518 but costs rear
  // coverage. 0.42 is the chosen point.
  const skirt = mesh(
    taperedPatch(
      HELMET_SKIRT,
      Math.PI / 2 + HELMET_FACE,
      Math.PI * 2 - HELMET_FACE * 2,
      Math.PI * 0.49,
      (across) => Math.PI * (0.745 - 0.067 * (1 - smoothstep(0, 0.42, Math.abs(Math.abs(across) - 0.665)))),
    ),
    "main",
    "helmet-side-skirt",
    skirtSeat,
  );
  // Closing the sides to the jaw still left the skull bare from the skirt's rim
  // down to its underside at -0.325 - the nape. This panel hangs below the
  // skirt's rear on the same ellipsoid, so it continues that surface rather than
  // sitting on it, and it closes to nothing at its own edges: a lens, not a
  // bracket. That is what keeps it out of the shoulders. Its depth is spent
  // straight back, where it reaches y -0.292 - the height at which the skull's
  // rear passes inside the neck, a 0.28-wide column against a back of the head
  // measuring z -0.142 there, so below it the body hides the skull anyway.
  const napeTop = Math.PI * 0.675;
  const nape = mesh(
    taperedPatch(
      HELMET_SKIRT,
      rear - 1.2,
      2.4,
      napeTop,
      (across) => napeTop + (Math.PI * 0.7618 - napeTop) * (1 - smoothstep(0.35, 1, Math.abs(across))),
    ),
    "main",
    "helmet-nape",
    skirtSeat,
  );
  // The glass fills the opening and tucks behind the frame; heights come from
  // y = -0.02 + 0.4 cos(theta) on the visor surface, so its top at y 0.052 laps
  // behind the crown's rim at 0.045 and its bottom at -0.156 laps behind the
  // chin guard's top at -0.158.
  const visorSeat: [number, number, number] = [0, HELMET_VISOR.y, HELMET_VISOR.z];
  const visor = mesh(
    helmetPatch(HELMET_VISOR, Math.PI / 2 - 0.79, 1.58, Math.PI * 0.4423, Math.PI * 0.1681, 0),
    "glass",
    "helmet-glass",
    visorSeat,
  );
  // Four bars around the opening, 0.008 proud of the glass, each covering one of
  // its seams against the shell.
  const visorBars: THREE.Object3D[] = [
    mesh(helmetPatch(HELMET_VISOR, Math.PI / 2 - 0.83, 1.66, Math.PI * 0.431, Math.PI * 0.0267, 0.008), "trim", "helmet-visor-frame-top", visorSeat),
    mesh(helmetPatch(HELMET_VISOR, Math.PI / 2 - 0.83, 1.66, Math.PI * 0.5989, Math.PI * 0.0194, 0.008), "trim", "helmet-visor-frame-base", visorSeat),
  ];
  for (const side of [-1, 1] as const) {
    const from = side > 0 ? Math.PI / 2 + 0.75 : Math.PI / 2 - 0.85;
    visorBars.push(
      mesh(helmetPatch(HELMET_VISOR, from, 0.1, Math.PI * 0.431, Math.PI * 0.1873, 0.008), "trim", `helmet-visor-frame-${side}`, visorSeat),
    );
  }
  // Cheek pads on the shell's own surface, straddling the edge of the face
  // opening. The flat extruded outline they replace stood up to 0.065u outside
  // the shell and read from the side as a grey box parked beside the cheek.
  const cheek = (side: -1 | 1) => {
    const from = side > 0 ? Math.PI / 2 + HELMET_FACE - 0.32 : Math.PI - (Math.PI / 2 + HELMET_FACE + 0.44);
    return mesh(
      helmetPatch(HELMET_SKIRT, from, 0.76, Math.PI * 0.51, Math.PI * 0.174, 0.008),
      "main",
      `helmet-cheek-${side}`,
      skirtSeat,
    );
  };
  const chinOuter = [[-0.245, 0.015], [0.245, 0.015], [0.22, -0.13], [0.145, -0.18], [-0.145, -0.18], [-0.22, -0.13]] as const;
  const chinVent = [[-0.115, -0.02], [0.115, -0.02], [0.095, -0.105], [-0.095, -0.105]] as const;
  // Lifted from -0.205 to -0.178 so its top edge meets the visor frame's lower
  // bar at y -0.165. At -0.205 a 0.02u strip of bare face showed between them.
  const chin = mesh(frameShape(chinOuter, chinVent, 0.044, 0.022), "main", "helmet-chin-guard", [0, -0.178, 0.282]);
  const lowerRim = mesh(line([[-0.205, -0.35, 0.288], [0, -0.38, 0.299], [0.205, -0.35, 0.288]], 0.015), "ink", "helmet-lower-rim");
  for (const x of [-0.075, -0.025, 0.025, 0.075]) {
    // Raised to sit inside the chin guard's vent opening (y -0.198 to -0.283)
    // instead of hanging below it, which left the top of the vent see-through.
    const bar = mesh(box(0.016, 0.075, 0.018, 0.005), "ink", `helmet-vent-bar-${x}`, [x, -0.2405, 0.325]);
    bar.rotation.z = x * 0.6;
    add(root, bar);
  }
  for (const side of [-1, 1] as const) {
    // A low rounded hinge is buried into the shell surface. The earlier tall
    // cylinder projected as detached rectangular hardware in profile.
    const hinge = mesh(ball(0.018, 0.03, 0.021, 16, 10), "steel", `helmet-flush-hinge-${side}`, [side * 0.326, -0.025, 0.158]);
    add(root, hinge);
  }
  // Three shallow intake slots recessed 0.004u into the crown, each laid along
  // the surface by the ellipsoid's own gradient there.
  for (const [index, [x, z]] of ([[0, 0.215], [-0.135, 0.085], [0.135, 0.085]] as const).entries()) {
    const y = helmetTop(x, z, -0.004);
    const vent = mesh(box(0.062, 0.014, 0.05, 0.005), "ink", `helmet-crown-vent-${index}`, [x, y, z]);
    const up = (y - HELMET_SHELL.y) / HELMET_SHELL.ry ** 2;
    vent.rotation.x = Math.atan2((z - HELMET_SHELL.z) / HELMET_SHELL.rz ** 2, up);
    vent.rotation.z = -Math.atan2(x / HELMET_SHELL.rx ** 2, up);
    add(root, vent);
  }
  // A spoiler ridge on the lower rear, placed by walking the polar angle round
  // the shell rather than by picking a z and hoping.
  const spoilerTheta = Math.PI * 0.55;
  const spoiler = mesh(ball(0.115, 0.088, 0.042, 20, 12), "trim", "helmet-rear-spoiler", [
    0,
    HELMET_SHELL.y + HELMET_SHELL.ry * Math.cos(spoilerTheta),
    HELMET_SHELL.z - HELMET_SHELL.rz * Math.sin(spoilerTheta),
  ]);
  const crownStripe = mesh(
    line(
      [-0.27, -0.14, 0, 0.14, 0.27].map((z) => [0, helmetTop(0, z, 0.004), z] as [number, number, number]),
      0.018,
    ),
    "trim",
    "helmet-crown-stripe",
  );
  add(root, cap, crownBand, skirt, nape, visor, ...visorBars, cheek(-1), cheek(1), chin, lowerRim, spoiler, crownStripe);
}

function crown(root: THREE.Group) {
  // A closed lower band seats on the skull; eight alternating points continue
  // around the whole circumference, so rear and profile views remain a crown.
  const band = mesh(new THREE.CylinderGeometry(0.318, 0.336, 0.14, 32), "metal", "crown-full-band", [0, 0.145, -0.012]);
  band.scale.z = 0.94;
  const lowerRim = mesh(torus(0.329, 0.022), "trim", "crown-lower-rim", [0, 0.074, -0.012]);
  lowerRim.rotation.x = Math.PI / 2;
  // Scale composes before rotation: a flat-lying torus squashes its world z
  // through LOCAL Y. scale.z here only thinned the tube and left the ring
  // circular around an ovoid skull.
  lowerRim.scale.y = 0.94;
  const upperRim = mesh(torus(0.316, 0.014), "cream", "crown-upper-rim", [0, 0.215, -0.012]);
  upperRim.rotation.x = Math.PI / 2;
  upperRim.scale.y = 0.94;
  add(root, band, lowerRim, upperRim);
  const pointCount = 8;
  for (let index = 0; index < pointCount; index += 1) {
    const angle = (index / pointCount) * Math.PI * 2;
    const isCardinal = index % 2 === 0;
    const tall = isCardinal ? 0.285 : 0.205;
    const radius = 0.296;
    const x = Math.sin(angle) * radius;
    const z = Math.cos(angle) * radius - 0.012;
    const point = mesh(shape([[-0.068, 0], [-0.034, tall * 0.48], [0, tall], [0.034, tall * 0.48], [0.068, 0]], 0.05), "metal", `crown-point-${index}`, [x, 0.205, z]);
    point.rotation.y = angle;
    const pearl = mesh(ball(isCardinal ? 0.033 : 0.026, isCardinal ? 0.033 : 0.026, 0.026), "cream", `crown-pearl-${index}`, [x, 0.205 + tall, z]);
    add(root, point, pearl);
  }
  const gems = [
    [-0.205, 0.14, 0.255, "trim"],
    [-0.105, 0.148, 0.302, "glow"],
    [0, 0.15, 0.318, "trim"],
    [0.105, 0.148, 0.302, "glow"],
    [0.205, 0.14, 0.255, "trim"],
  ] as const;
  for (const [index, [x, y, z, tint]] of gems.entries()) {
    const bezel = mesh(ball(0.051, 0.062, 0.018), "cream", `crown-bezel-${index}`, [x, y, z]);
    const gem = mesh(new THREE.OctahedronGeometry(index === 2 ? 0.044 : 0.036, 0), tint, `crown-gem-${index}`, [x, y, z + 0.018]);
    gem.scale.y = 1.22;
    add(root, bezel, gem);
  }
}

function cowboy(root: THREE.Group) {
  // The brim is a closed oval annulus with raised side curls, not a single
  // left-to-right tube. Its inner edge stays seated under the crown.
  const brim = mesh(curledOvalBrim(), "main", "cowboy-complete-brim", [0, 0.03, -0.015]);
  // The crown was 0.275 wide with a 0.86 z squash, which puts its wall at z 0.236
  // against a skull that measures 0.270 at the same height: the forehead and the
  // back of the head came through the crown between y 0.16 and y 0.23, which is
  // the clipping the player reported. 0.305 with a 0.955 squash clears the skull
  // by 0.022 in x and 0.009 in z, and the extra 0.025u of height puts the
  // interior above the skull's own crest at y 0.325 with room for hair.
  const crown = mesh(new THREE.CylinderGeometry(0.255, 0.305, 0.255, 28), "main", "cowboy-crown", [0, 0.2875, -0.012]);
  crown.scale.z = 0.955;
  // Two raised lobes and a recessed centre establish the pinched western crown
  // without painting a contrast-coloured box down its face. Their undersides sit
  // at y 0.363, clear of the skull crest at 0.325 and of the hair cap at 0.338.
  const crownLeft = mesh(ball(0.148, 0.055, 0.2), "main", "cowboy-crown-lobe-left", [-0.09, 0.418, -0.022]);
  const crownRight = mesh(ball(0.148, 0.055, 0.2), "main", "cowboy-crown-lobe-right", [0.09, 0.418, -0.022]);
  const crease = mesh(line([[0, 0.434, -0.177], [0, 0.412, -0.012], [0, 0.432, 0.148]], 0.011), "trim", "cowboy-top-crease");
  const band = mesh(torus(0.307, 0.02), "trim", "cowboy-band", [0, 0.176, -0.012]);
  band.rotation.x = Math.PI / 2;
  band.scale.y = 0.955;
  // On the band's front face, which the squash puts at z -0.012 + (0.307 + 0.02)
  // * 0.955 = 0.300.
  const buckle = mesh(box(0.07, 0.052, 0.018, 0.012), "steel", "cowboy-buckle", [0, 0.178, 0.296]);
  add(root, brim, crown, crownLeft, crownRight, crease, band, buckle);
}

/** Where a point of the beret's crown ends up once the cloth slumps to one side. */
function beretSlump(x: number, y: number): [number, number] {
  const side = Math.min(1, Math.max(-1, -x / BERET_CROWN.rx));
  const sag = Math.max(0, side) ** 1.7;
  const lift = Math.max(0, -side) ** 1.7;
  return [x - 0.036 * sag, y - 0.062 * sag + 0.026 * lift];
}
function slumped(geometry: THREE.BufferGeometry) {
  const position = geometry.getAttribute("position") as THREE.BufferAttribute;
  for (let index = 0; index < position.count; index += 1) {
    const [x, y] = beretSlump(position.getX(index), position.getY(index));
    position.setXY(index, x, y);
  }
  position.needsUpdate = true;
  geometry.computeVertexNormals();
  return geometry;
}

const BERET_CROWN = { rx: 0.352, ry: 0.128, rz: 0.33, y: 0.268, z: -0.02 };

function beret(root: THREE.Group) {
  // A real sweatband with height, a rolled lip at the seam, and a crown that
  // sags towards the left ear with its far edge lifted. The item it replaces was
  // a symmetric squashed ellipsoid over a 0.014u wire ring, which reads as a
  // plate resting on the head rather than as cloth.
  //
  // The band clears the skull by 0.012u: at its lower edge, y 0.148, the skull
  // measures x 0.290 and z 0.277, and 0.302 with a 0.96 z squash gives 0.302 by
  // 0.290. The 0.93 squash it replaces pinched inside that.
  const band = mesh(new THREE.CylinderGeometry(0.302, 0.302, 0.064, 30, 1, true), "trim", "beret-sweatband", [0, 0.18, -0.012]);
  band.scale.z = 0.96;
  const lip = mesh(torus(0.308, 0.017), "trim", "beret-rolled-lip", [0, 0.212, -0.012]);
  lip.rotation.x = Math.PI / 2;
  // Scale composes before rotation, so the world-z squash of a flat-lying torus
  // has to go through LOCAL y.
  lip.scale.y = 0.96;
  const crown = mesh(
    slumped(ball(BERET_CROWN.rx, BERET_CROWN.ry, BERET_CROWN.rz, 34, 20)),
    "main",
    "beret-slumped-crown",
    [0, BERET_CROWN.y, BERET_CROWN.z],
  );
  add(root, band, lip, crown);
  // Gather folds running from the band up to the stalk, laid on the crown's own
  // surface and passed through the same slump so they travel with the cloth.
  for (const [index, angle] of [0.5, 1.9, 3.4, 4.9].entries()) {
    const path = [1.25, 0.45, -0.42].map((tilt) => {
      const flat = Math.cos(tilt);
      const [x, y] = beretSlump(BERET_CROWN.rx * flat * Math.sin(angle), BERET_CROWN.ry * Math.sin(tilt));
      return [x, BERET_CROWN.y + y, BERET_CROWN.z + BERET_CROWN.rz * flat * Math.cos(angle)] as [number, number, number];
    });
    add(root, mesh(line(path, 0.008, 16), "trim", `beret-gather-${index}`));
  }
  const [stalkX, stalkY] = beretSlump(0.03, BERET_CROWN.ry * 0.996);
  const stalk = mesh(new THREE.CylinderGeometry(0.011, 0.017, 0.05, 10), "trim", "beret-stalk", [
    stalkX,
    BERET_CROWN.y + stalkY + 0.02,
    BERET_CROWN.z,
  ]);
  add(root, stalk);
}

function earmuffs(root: THREE.Group) {
  // A padded band over the crown, a U-yoke per side, and cups built as a shell
  // with a separate cushion pressed against the head. Ear centres are read off
  // the rig rather than assumed: the Ear meshes box x 0.291 to 0.369 and y -0.142
  // to -0.022, so an ear sits at (+-0.330, -0.082, -0.010).
  //
  // The arc radius is 0.385 and the tube 0.026, so the band's inner face rides
  // 0.034 above the skull crest at 0.325 and 0.021 above the hair cap at 0.338.
  // It has to clear the hair as well as the skull: earmuffs are one of the items
  // that leave a chosen hairstyle visible.
  const bandRadius = 0.385;
  const arc = [-1.3, -0.975, -0.65, -0.325, 0, 0.325, 0.65, 0.975, 1.3].map(
    (angle) => [bandRadius * Math.sin(angle), bandRadius * Math.cos(angle), -0.03] as [number, number, number],
  );
  add(root, mesh(line(arc, 0.026, 30), "main", "earmuff-padded-band"));
  for (const side of [-1, 1] as const) {
    // Two arms straddling the cup, bridging the band's end at y 0.103 down to
    // the cup's crown at y 0.028, with a pivot pin across them.
    for (const [index, z] of [-0.072, 0.012].entries()) {
      add(root, mesh(box(0.02, 0.11, 0.018, 0.006), "steel", `earmuff-yoke-arm-${side}-${index}`, [side * 0.372, 0.062, z]));
    }
    const pivot = mesh(new THREE.CylinderGeometry(0.019, 0.019, 0.1, 12), "steel", `earmuff-yoke-pivot-${side}`, [side * 0.372, 0.028, -0.03]);
    pivot.rotation.x = Math.PI / 2;
    const shell = mesh(ball(0.062, 0.112, 0.095, 22, 14), "trim", `earmuff-cup-shell-${side}`, [side * 0.383, -0.082, -0.012]);
    // The cushion is its own ring seated on the head, not a face of the shell:
    // its hole is 0.088 across against an ear 0.078 by 0.120, so it closes round
    // the ear instead of hovering beside it.
    const cushion = mesh(torus(0.074, 0.03), "cream", `earmuff-cushion-${side}`, [side * 0.334, -0.082, -0.012]);
    cushion.rotation.y = Math.PI / 2;
    add(root, pivot, shell, cushion);
  }
}

function grin(root: THREE.Group) {
  // A compact, slightly crooked smile follows the lower face. The tooth flash
  // occupies only the upper half of the cavity instead of becoming a mouthguard.
  const mouthOuter = [[-0.09, 0.015], [-0.052, 0.032], [0.005, 0.038], [0.058, 0.032], [0.092, 0.022], [0.07, -0.025], [0.028, -0.048], [-0.008, -0.052], [-0.045, -0.042], [-0.076, -0.018]] as const;
  const mouthInner = [[-0.073, 0.008], [-0.042, 0.021], [0.004, 0.026], [0.047, 0.022], [0.074, 0.014], [0.054, -0.016], [0.023, -0.032], [-0.007, -0.036], [-0.036, -0.029], [-0.06, -0.012]] as const;
  const cavity = mesh(curvedShape(mouthInner, 0.005, 0.007), "ink", "grin-small-cavity", [0, -0.172, 0.287]);
  const lip = mesh(frameShape(mouthOuter, mouthInner, 0.007, 0.007), "ink", "grin-small-curved-lip", [0, -0.172, 0.291]);
  const toothBed = mesh(curvedShape([[-0.057, 0.011], [-0.025, 0.017], [0.008, 0.019], [0.052, 0.014], [0.045, -0.009], [0.012, -0.017], [-0.022, -0.014], [-0.05, -0.006]], 0.004, 0.006), "cream", "grin-tooth-flash", [0, -0.169, 0.296]);
  add(root, cavity, toothBed, lip);
  for (const x of [-0.022, 0.012]) {
    const separator = mesh(box(0.004, 0.026, 0.003, 0.0015), "ink", `grin-tooth-gap-${x}`, [x, -0.166, 0.304]);
    separator.rotation.z = -0.04 - x * 0.45;
    add(root, separator);
  }
}

function beard(root: THREE.Group) {
  // Lofted off the skull rather than stood in front of it. Elevations are the
  // rig's own landmarks turned into angles by v = asin(y / 0.325):
  //   eye        y -0.076 -> -0.235      mouth top    y -0.144 -> -0.455
  //   cheek line y -0.110 -> -0.345      mouth bottom y -0.174 -> -0.556
  //   jaw hinge  y -0.198 -> -0.660      chin under   y -0.318 -> -1.360
  // The jaw panel's top edge sits under the mouth at the front and climbs to the
  // cheek line at the sides; the moustache panel bridges above the mouth and
  // droops at its ends into that climb, so the two together enclose the mouth in
  // one loop instead of leaving it floating in an open U.
  const uMax = 1.22;
  const jawTop = (u: number) => -0.615 + 0.27 * smoothstep(0.24, 0.44, Math.abs(u));
  // -1.02 rather than the -1.36 that would carry the loft round to the throat.
  // A panel lofted onto the skull travels through the collar volume on its way
  // under the chin, and wardrobe.test.ts fails any head garment inside the shirt
  // once the head twists: at -1.36 the underside reached y -0.363, which lands
  // at world 1.226 against a 1.23 ceiling. -1.02 ends the loft on the underside
  // of the chin at y -0.317, world 1.243.
  const jawBottom = (u: number) => -1.02 + 0.36 * smoothstep(0, uMax, Math.abs(u));
  const jawSwell = (u: number, s: number) =>
    0.006 + 0.04 * smoothstep(0, 0.32, s) * (0.62 + 0.38 * smoothstep(0, 0.26, 1 - Math.abs(u) / uMax));
  const jaw = mesh(facePanel(uMax, jawTop, jawBottom, jawSwell), "main", "beard-jaw-loft");
  // The rig gives a moustache no clear room: the nose ends at y -0.1455 and the
  // mouth starts at -0.1436. The bridge therefore tucks its thin top edge under
  // the nose and stops at y -0.153, which leaves the lower two thirds of the
  // mouth open. Its ends droop past the jaw panel's top edge so the two pieces
  // overlap at the corner of the mouth rather than meeting on a hairline.
  const lipMax = 0.3;
  const lipTop = () => -0.395;
  const lipBottom = (u: number) => -0.44 - 0.16 * (Math.abs(u) / lipMax) ** 2;
  const lipSwell = (u: number, s: number) =>
    0.008 + 0.026 * smoothstep(0, 0.35, s) * (0.6 + 0.4 * smoothstep(0, 0.3, 1 - Math.abs(u) / lipMax));
  const moustache = mesh(
    facePanel(lipMax, lipTop, lipBottom, lipSwell, 0.004, 20, 10),
    "main",
    "beard-moustache-bridge",
  );
  add(root, jaw, moustache);
  // Rounded volumes seated on the same surface, so they soften the silhouette
  // from inside the loft instead of separating from it.
  const chin = mesh(ball(0.088, 0.048, 0.04, 22, 14), "main", "beard-chin-mass", facePoint(0, -0.95, 0.004));
  add(root, chin);
  for (const side of [-1, 1] as const) {
    const jowl = mesh(ball(0.062, 0.05, 0.036, 20, 12), "main", `beard-jowl-${side}`, facePoint(side * 0.6, -0.86, 0.004));
    // At v -0.44 this ball topped out at y -0.081, level with the eye at -0.076
    // and the exact "climbs to eye level" note on the old beard. Dropped to
    // v -0.50 and shortened, it now tops out at -0.107, under the panel's own
    // cheek edge.
    const sideburn = mesh(ball(0.032, 0.05, 0.026, 18, 12), "main", `beard-sideburn-${side}`, facePoint(side * 1.04, -0.5, 0.002));
    add(root, jowl, sideburn);
  }
}

function mask(root: THREE.Group) {
  const outline = [[-0.185, 0.06], [-0.105, 0.087], [0, 0.095], [0.105, 0.087], [0.185, 0.06], [0.16, -0.085], [0.085, -0.13], [0, -0.142], [-0.085, -0.13], [-0.16, -0.085]] as const;
  const cover = mesh(curvedShape(outline, 0.012, 0.026), "main", "mask-soft-cover", [0, -0.15, 0.294]);
  add(root, cover);
  // Curved pleat cords follow the face instead of hovering as straight slats.
  add(root, mesh(line([[-0.142, -0.08, 0.306], [0, -0.068, 0.326], [0.142, -0.08, 0.306]], 0.005), "cream", "mask-nose-strip"));
  for (const [index, y] of [-0.142, -0.18, -0.215].entries()) {
    const pleat = mesh(line([[-0.145 + index * 0.01, y, 0.309], [0, y + 0.007, 0.329], [0.145 - index * 0.01, y, 0.309]], 0.0035), "trim", `mask-pleat-${index}`);
    add(root, pleat);
  }
  for (const side of [-1, 1] as const) {
    const edge = mesh(line([[side * 0.182, -0.095, 0.299], [side * 0.17, -0.165, 0.305], [side * 0.15, -0.235, 0.299]], 0.005), "trim", `mask-edge-${side}`);
    add(root, edge);
  }
  // Separate upper and lower straps converge on the ear rather than looping
  // behind the head and returning as a rigid triangular cage.
  for (const side of [-1, 1] as const) {
    const ear = [side * 0.305, -0.145, 0.045] as const;
    const upper = mesh(line([[side * 0.18, -0.095, 0.299], [side * 0.255, -0.11, 0.175], ear], 0.0045), "cream", `mask-upper-strap-${side}`);
    const lower = mesh(line([[side * 0.15, -0.235, 0.299], [side * 0.245, -0.19, 0.15], ear], 0.0045), "cream", `mask-lower-strap-${side}`);
    add(root, upper, lower);
  }
}

function goggles(root: THREE.Group) {
  const outer = [[-0.235, 0.078], [-0.17, 0.102], [0.17, 0.102], [0.235, 0.078], [0.215, -0.063], [0.145, -0.092], [0.04, -0.086], [0, -0.045], [-0.04, -0.086], [-0.145, -0.092], [-0.215, -0.063]] as const;
  const window = [[-0.211, 0.059], [-0.155, 0.079], [0.155, 0.079], [0.211, 0.059], [0.19, -0.045], [0.132, -0.066], [0.034, -0.061], [0, -0.022], [-0.034, -0.061], [-0.132, -0.066], [-0.19, -0.045]] as const;
  const lens = mesh(curvedShape(window, 0.008, 0.027), "glass", "ski-goggle-unified-lens", [0, -0.072, 0.307]);
  const rim = mesh(frameShape(outer, window, 0.015, 0.027), "main", "ski-goggle-soft-rim", [0, -0.072, 0.304]);
  const strap = mesh(torus(0.337, 0.019), "trim", "ski-goggle-strap", [0, -0.066, -0.012]);
  strap.rotation.x = Math.PI / 2;
  // 0.90, not the 0.98 that shipped: the strap ring stood 0.046u proud of
  // the skull fore and aft and read as a rod skewering the head.
  strap.scale.y = 0.90;
  add(root, strap, lens, rim);
  for (const side of [-1, 1] as const) {
    const buckle = mesh(box(0.032, 0.056, 0.018, 0.008), "steel", `ski-goggle-buckle-${side}`, [side * 0.3, -0.068, 0.185]);
    buckle.rotation.y = side * 0.32;
    add(root, buckle);
  }
}

function aviator(root: THREE.Group) {
  const rimOuter = [[-0.09, 0.068], [0.09, 0.068], [0.092, 0.018], [0.065, -0.064], [0.024, -0.108], [0, -0.12], [-0.024, -0.108], [-0.065, -0.064], [-0.092, 0.018]] as const;
  const lensShape = [[-0.073, 0.051], [0.073, 0.051], [0.075, 0.015], [0.052, -0.052], [0.018, -0.09], [0, -0.101], [-0.018, -0.09], [-0.052, -0.052], [-0.075, 0.015]] as const;
  for (const side of [-1, 1] as const) {
    const lens = mesh(curvedShape(lensShape, 0.007, 0.01), "glass", `aviator-glass-${side}`, [side * 0.108, -0.076, 0.316]);
    const rim = mesh(frameShape(rimOuter, lensShape, 0.012, 0.01), "main", `aviator-teardrop-rim-${side}`, [side * 0.108, -0.076, 0.32]);
    lens.rotation.z = rim.rotation.z = -side * 0.035;
    add(root, lens, rim);
  }
  const bridge = mesh(line([[-0.027, -0.047, 0.331], [0, -0.029, 0.34], [0.027, -0.047, 0.331]], 0.007), "main", "aviator-lower-bridge");
  const brow = mesh(line([[-0.195, -0.014, 0.307], [-0.105, 0.004, 0.331], [0, 0.008, 0.34], [0.105, 0.004, 0.331], [0.195, -0.014, 0.307]], 0.006), "main", "aviator-upper-bridge");
  add(root, bridge, brow);
  for (const side of [-1, 1] as const) {
    const arm = mesh(line([[side * 0.198, -0.05, 0.314], [side * 0.255, -0.06, 0.235], [side * 0.295, -0.07, 0.13]], 0.006), "main", `aviator-temple-${side}`);
    add(root, arm);
  }
}

function visorband(root: THREE.Group) {
  const shield = [[-0.292, 0.082], [-0.22, 0.112], [0.22, 0.112], [0.292, 0.082], [0.26, -0.055], [0.14, -0.092], [0, -0.105], [-0.14, -0.092], [-0.26, -0.055]] as const;
  const lens = mesh(curvedShape(shield, 0.006, 0.038), "glass", "future-visor-thin-glass-shield", [0, -0.073, 0.307]);
  lens.renderOrder = 2;
  const brow = mesh(line([[-0.275, 0.012, 0.321], [-0.14, 0.034, 0.344], [0, 0.042, 0.354], [0.14, 0.034, 0.344], [0.275, 0.012, 0.321]], 0.006), "trim", "future-visor-brow");
  add(root, lens, brow);
  for (const side of [-1, 1] as const) {
    const temple = mesh(line([[side * 0.275, -0.072, 0.317], [side * 0.322, -0.068, 0.218], [side * 0.33, -0.075, 0.11]], 0.008), "main", `future-visor-temple-${side}`);
    const hinge = mesh(new THREE.CylinderGeometry(0.025, 0.025, 0.02, 14), "steel", `future-visor-hinge-${side}`, [side * 0.331, -0.073, 0.11]);
    hinge.rotation.z = Math.PI / 2;
    const hingeInset = mesh(new THREE.CylinderGeometry(0.011, 0.011, 0.023, 12), "trim", `future-visor-hinge-inset-${side}`, [side * 0.332, -0.073, 0.11]);
    hingeInset.rotation.z = Math.PI / 2;
    add(root, temple, hinge, hingeInset);
  }
}

export function createHeadwearUpgradeModel(id: HeadwearUpgradeId): THREE.Group {
  const root = new THREE.Group();
  root.name = `headwear-upgrade:${id}`;
  switch (id) {
    case "helmet": helmet(root); break;
    case "crown": crown(root); break;
    case "cowboy": cowboy(root); break;
    case "beret": beret(root); break;
    case "earmuffs": earmuffs(root); break;
    case "grin": grin(root); break;
    case "beard": beard(root); break;
    case "mask": mask(root); break;
    case "goggles": goggles(root); break;
    case "aviator": aviator(root); break;
    case "visorband": visorband(root); break;
  }
  return root;
}
