"""Author the reference-led head, face, and eyewear rebuild wave.

This file is the deterministic author source. The generated TypeScript is
runtime output and must not be edited by hand. Forms are measured against the
runner head socket and the reference sheet listed in the adjacent manifest.
"""

from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[3]
HERE = Path(__file__).resolve().parent

SPEC = {
    "pipeline": "img2threejs reference -> measured head-socket sculpt -> generated runtime factory",
    "referenceSheet": "assets/reference/headwear-upgrades/headwear-face-eyewear-reference.png",
    "items": [
        "helmet", "crown", "cowboy", "beret", "grin", "beard", "mask",
        "goggles", "aviator", "visorband",
    ],
    "fitBasis": "HEAD measurements and silhouette gates in createWardrobeModels.ts",
    "frontAxis": "+Z",
    "reviewStatus": "generated structural pass; multi-angle runtime review required",
}

SOURCE = r'''// GENERATED by assets/reference/headwear-upgrades/author_headwear_upgrades.py
// Reference manifest: assets/reference/headwear-upgrades/headwear-upgrade-spec.json
import * as THREE from "three";

export type HeadwearUpgradeId = "helmet" | "crown" | "cowboy" | "beret" | "grin" | "beard" | "mask" | "goggles" | "aviator" | "visorband";
type Tint = "main" | "trim" | "ink" | "cream" | "steel" | "glow";

const placeholder = new THREE.MeshStandardMaterial({ color: 0xffffff, side: THREE.DoubleSide });
function mesh(geometry: THREE.BufferGeometry, tint: Tint, name: string, position: [number, number, number] = [0, 0, 0]) {
  const value = new THREE.Mesh(geometry, placeholder);
  value.name = `head-upgrade:${name}`;
  value.position.set(...position);
  value.userData["wardrobeTint"] = tint;
  value.castShadow = true;
  value.receiveShadow = true;
  value.raycast = () => undefined;
  return value;
}
function add(root: THREE.Group, ...parts: THREE.Object3D[]) { root.add(...parts); }
function ball(x: number, y: number, z: number, width = 22, height = 14) {
  const geometry = new THREE.SphereGeometry(1, width, height);
  geometry.scale(x, y, z);
  return geometry;
}
function box(x: number, y: number, z: number, bevel = 0.01) {
  const shape = new THREE.Shape();
  const hx = x / 2, hy = y / 2, r = Math.min(bevel, hx, hy);
  shape.moveTo(-hx + r, -hy); shape.lineTo(hx - r, -hy); shape.quadraticCurveTo(hx, -hy, hx, -hy + r);
  shape.lineTo(hx, hy - r); shape.quadraticCurveTo(hx, hy, hx - r, hy); shape.lineTo(-hx + r, hy);
  shape.quadraticCurveTo(-hx, hy, -hx, hy - r); shape.lineTo(-hx, -hy + r); shape.quadraticCurveTo(-hx, -hy, -hx + r, -hy);
  const geometry = new THREE.ExtrudeGeometry(shape, { depth: z, bevelEnabled: true, bevelSize: r * 0.45, bevelThickness: r * 0.45, bevelSegments: 2, curveSegments: 5 });
  geometry.translate(0, 0, -z / 2);
  return geometry;
}
function shape(points: readonly (readonly [number, number])[], depth = 0.018) {
  const outline = new THREE.Shape();
  outline.moveTo(points[0]![0], points[0]![1]);
  for (const [x, y] of points.slice(1)) outline.lineTo(x, y);
  outline.closePath();
  const geometry = new THREE.ExtrudeGeometry(outline, { depth, bevelEnabled: true, bevelSize: 0.006, bevelThickness: 0.004, bevelSegments: 2 });
  geometry.translate(0, 0, -depth / 2);
  return geometry;
}
function torus(radius: number, tube: number, arc = Math.PI * 2) {
  return new THREE.TorusGeometry(radius, tube, 7, Math.max(12, Math.round(arc * 7)), arc);
}

function helmet(root: THREE.Group) {
  // A full-face motorcycle silhouette: crown shell, swept jaw guards, dark
  // visor and separate chin bar. The opening remains visible from the side.
  const shellGeometry = new THREE.SphereGeometry(1, 28, 18, 0, Math.PI * 2, 0, Math.PI * 0.61);
  shellGeometry.scale(0.386, 0.37, 0.378);
  const shell = mesh(shellGeometry, "main", "helmet-shell", [0, 0.075, -0.02]);
  const visor = mesh(shape([[-0.28, 0.06], [0.28, 0.06], [0.245, -0.075], [-0.225, -0.075]], 0.026), "ink", "helmet-visor", [0, 0.015, 0.365]);
  visor.rotation.x = -0.08;
  const chin = mesh(shape([[-0.255, 0.045], [0.255, 0.045], [0.205, -0.09], [-0.19, -0.09]], 0.078), "main", "helmet-chin", [0, -0.225, 0.255]);
  chin.rotation.x = -0.11;
  const jaw = (side: -1 | 1) => {
    const guard = mesh(shape([[0, 0.12], [side * 0.07, 0.07], [side * 0.055, -0.13], [side * -0.025, -0.095]], 0.075), "main", `helmet-jaw-${side}`, [side * 0.28, -0.115, 0.205]);
    guard.rotation.y = side * 0.18;
    return guard;
  };
  const vent = mesh(box(0.13, 0.025, 0.018, 0.007), "trim", "helmet-vent", [0, -0.245, 0.307]);
  const stripe = mesh(box(0.055, 0.31, 0.018, 0.008), "trim", "helmet-stripe", [0, 0.245, 0.282]);
  stripe.rotation.x = -0.54;
  add(root, shell, visor, chin, jaw(-1), jaw(1), vent, stripe);
}

function crown(root: THREE.Group) {
  // Five broad heraldic points read as a crown, avoiding the old forest of
  // skinny cones. The front gems establish a clear face direction.
  const base = mesh(new THREE.CylinderGeometry(0.31, 0.335, 0.12, 26, 1, true), "main", "crown-band", [0, 0.145, -0.012]);
  const rim = mesh(torus(0.326, 0.025), "trim", "crown-rim", [0, 0.085, -0.012]);
  rim.rotation.x = Math.PI / 2;
  add(root, base, rim);
  const frontAngles = [-0.86, -0.43, 0, 0.43, 0.86];
  for (const [index, angle] of frontAngles.entries()) {
    const side = Math.sin(angle);
    const depth = Math.cos(angle);
    const tall = index === 2 ? 0.31 : index % 2 ? 0.23 : 0.27;
    const point = mesh(shape([[-0.065, 0], [0, tall], [0.065, 0]], 0.045), "main", `crown-point-${index}`, [side * 0.29, 0.20, depth * 0.29 - 0.012]);
    point.rotation.y = angle;
    const pearl = mesh(ball(0.032, 0.032, 0.032), "cream", `crown-pearl-${index}`, [side * 0.29, 0.20 + tall, depth * 0.29 - 0.012]);
    add(root, point, pearl);
  }
  for (const [index, x] of [-0.14, 0, 0.14].entries()) {
    const gem = mesh(new THREE.OctahedronGeometry(index === 1 ? 0.05 : 0.042, 0), index === 1 ? "glow" : "trim", `crown-gem-${index}`, [x, 0.14, 0.315]);
    gem.scale.y = 1.25;
    add(root, gem);
  }
}

function cowboy(root: THREE.Group) {
  // Front/back brim tips lift while the side edges remain low, giving the hat
  // an unmistakable western curl instead of a flat disc.
  const brimCurve = new THREE.CatmullRomCurve3([
    new THREE.Vector3(-0.43, 0.14, 0), new THREE.Vector3(-0.25, 0.09, 0),
    new THREE.Vector3(0, 0.075, 0), new THREE.Vector3(0.25, 0.09, 0),
    new THREE.Vector3(0.43, 0.14, 0),
  ]);
  const brim = mesh(new THREE.TubeGeometry(brimCurve, 28, 0.055, 8, false), "main", "cowboy-curled-brim", [0, 0, -0.01]);
  brim.scale.z = 3.2;
  const crown = mesh(new THREE.CylinderGeometry(0.235, 0.285, 0.30, 24), "main", "cowboy-crown", [0, 0.27, -0.025]);
  crown.scale.z = 0.88;
  const crease = mesh(box(0.07, 0.22, 0.31, 0.024), "trim", "cowboy-crease", [0, 0.33, -0.025]);
  const band = mesh(torus(0.272, 0.021), "trim", "cowboy-band", [0, 0.145, -0.02]);
  band.rotation.x = Math.PI / 2;
  add(root, brim, crown, crease, band);
}

function beret(root: THREE.Group) {
  const cap = mesh(ball(0.35, 0.10, 0.33), "main", "beret-soft-cap", [-0.035, 0.285, -0.045]);
  cap.rotation.z = 0.17;
  const headband = mesh(torus(0.30, 0.022), "trim", "beret-headband", [0, 0.205, -0.02]);
  headband.rotation.x = Math.PI / 2;
  const stalk = mesh(new THREE.CylinderGeometry(0.012, 0.018, 0.06, 10), "trim", "beret-stalk", [0.06, 0.407, -0.055]);
  stalk.rotation.z = -0.35;
  add(root, cap, headband, stalk);
}

function grin(root: THREE.Group) {
  // A thin smile line and five small teeth sit completely in front of the
  // nose/mouth plane instead of becoming a white mouthguard.
  const smile = mesh(torus(0.085, 0.012, Math.PI), "ink", "grin-smile", [0, -0.176, 0.327]);
  smile.rotation.z = Math.PI;
  smile.rotation.x = Math.PI / 2;
  add(root, smile);
  for (let index = 0; index < 5; index += 1) {
    const tooth = mesh(box(0.026, 0.028, 0.01, 0.005), "cream", `grin-tooth-${index}`, [-0.052 + index * 0.026, -0.183, 0.337]);
    add(root, tooth);
  }
}

function beard(root: THREE.Group) {
  // Separate cheek/chin tufts form a U with a generous mouth opening.
  for (const side of [-1, 1] as const) {
    const cheek = mesh(shape([[0, 0.06], [side * 0.07, 0.025], [side * 0.08, -0.08], [side * 0.025, -0.055]], 0.03), "main", `beard-cheek-${side}`, [side * 0.115, -0.165, 0.304]);
    cheek.rotation.z = side * 0.08;
    const lower = mesh(shape([[0, 0.035], [side * 0.09, 0], [side * 0.04, -0.105], [0, -0.08]], 0.032), "main", `beard-lower-${side}`, [side * 0.06, -0.232, 0.292]);
    add(root, cheek, lower);
  }
  const chin = mesh(shape([[-0.07, 0.04], [0.07, 0.04], [0.045, -0.105], [0, -0.135], [-0.045, -0.105]], 0.034), "main", "beard-chin", [0, -0.242, 0.296]);
  add(root, chin);
}

function mask(root: THREE.Group) {
  const cover = mesh(shape([[-0.20, 0.065], [0.20, 0.065], [0.15, -0.09], [0, -0.135], [-0.15, -0.09]], 0.028), "main", "mask-cover", [0, -0.16, 0.328]);
  add(root, cover);
  // One fitted nose strip and two same-fabric folds preserve the surgical-mask
  // read without the old high-contrast slats looking like a wooden muzzle.
  add(root, mesh(box(0.25, 0.009, 0.012, 0.004), "cream", "mask-nose-strip", [0, -0.105, 0.346]));
  for (const y of [-0.16, -0.20]) add(root, mesh(box(0.245, 0.006, 0.01, 0.003), "main", `mask-pleat-${y}`, [0, y, 0.347]));
  for (const side of [-1, 1] as const) {
    const curve = new THREE.CatmullRomCurve3([
      new THREE.Vector3(side * 0.19, -0.12, 0.324),
      new THREE.Vector3(side * 0.275, -0.13, 0.20),
      new THREE.Vector3(side * 0.285, -0.18, 0.07),
      new THREE.Vector3(side * 0.19, -0.22, 0.31),
    ]);
    add(root, mesh(new THREE.TubeGeometry(curve, 18, 0.006, 6, false), "cream", `mask-loop-${side}`));
  }
}

function goggles(root: THREE.Group) {
  const lens = mesh(shape([[-0.235, 0.075], [-0.025, 0.09], [0, 0.055], [0.025, 0.09], [0.235, 0.075], [0.205, -0.07], [0.03, -0.08], [0, -0.055], [-0.03, -0.08], [-0.205, -0.07]], 0.028), "steel", "ski-goggle-lens", [0, -0.075, 0.345]);
  const rim = mesh(shape([[-0.26, 0.09], [-0.025, 0.11], [0, 0.075], [0.025, 0.11], [0.26, 0.09], [0.225, -0.09], [0.03, -0.105], [0, -0.075], [-0.03, -0.105], [-0.225, -0.09]], 0.018), "main", "ski-goggle-frame", [0, -0.075, 0.333]);
  const inner = mesh(shape([[-0.225, 0.064], [-0.02, 0.078], [0, 0.045], [0.02, 0.078], [0.225, 0.064], [0.195, -0.064], [0.025, -0.075], [0, -0.048], [-0.025, -0.075], [-0.195, -0.064]], 0.024), "steel", "ski-goggle-window", [0, -0.075, 0.35]);
  const strap = mesh(torus(0.342, 0.032), "trim", "ski-goggle-strap", [0, -0.068, -0.012]);
  strap.rotation.x = Math.PI / 2;
  add(root, strap, rim, lens, inner);
}

function aviator(root: THREE.Group) {
  const lensShape = [[-0.066, 0.055], [0.055, 0.055], [0.065, 0.005], [0.025, -0.07], [-0.025, -0.07], [-0.065, 0.005]] as const;
  for (const side of [-1, 1] as const) {
    const lens = mesh(shape(lensShape, 0.02), "steel", `aviator-lens-${side}`, [side * 0.102, -0.075, 0.347]);
    lens.rotation.z = -side * 0.06;
    const rim = mesh(torus(0.07, 0.011), "main", `aviator-rim-${side}`, [side * 0.105, -0.074, 0.35]);
    rim.scale.y = 0.78;
    add(root, lens, rim);
  }
  const bridge = mesh(torus(0.052, 0.009, Math.PI), "main", "aviator-bridge", [0, -0.052, 0.36]);
  bridge.rotation.z = Math.PI;
  add(root, bridge);
  for (const side of [-1, 1] as const) {
    const arm = mesh(box(0.16, 0.017, 0.018, 0.006), "main", `aviator-arm-${side}`, [side * 0.225, -0.07, 0.285]);
    arm.rotation.y = side * 0.7;
    add(root, arm);
  }
}

function visorband(root: THREE.Group) {
  const lens = mesh(shape([[-0.29, 0.065], [-0.21, 0.10], [0.21, 0.10], [0.29, 0.065], [0.235, -0.07], [-0.19, -0.07]], 0.025), "main", "future-visor-lens", [0, -0.072, 0.35]);
  add(root, lens);
  for (const side of [-1, 1] as const) {
    const connector = mesh(box(0.14, 0.04, 0.035, 0.012), "trim", `future-visor-arm-${side}`, [side * 0.32, -0.072, 0.245]);
    connector.rotation.y = side * 0.72;
    const hinge = mesh(new THREE.CylinderGeometry(0.035, 0.035, 0.025, 14), "steel", `future-visor-hinge-${side}`, [side * 0.342, -0.072, 0.14]);
    hinge.rotation.z = Math.PI / 2;
    add(root, connector, hinge);
  }
}

export function createHeadwearUpgradeModel(id: HeadwearUpgradeId): THREE.Group {
  const root = new THREE.Group();
  root.name = `headwear-upgrade:${id}`;
  switch (id) {
    case "helmet": helmet(root); break;
    case "crown": crown(root); break;
    case "cowboy": cowboy(root); break;
    case "beret": beret(root); break;
    case "grin": grin(root); break;
    case "beard": beard(root); break;
    case "mask": mask(root); break;
    case "goggles": goggles(root); break;
    case "aviator": aviator(root); break;
    case "visorband": visorband(root); break;
  }
  return root;
}
'''


def main() -> None:
    (HERE / "headwear-upgrade-spec.json").write_text(json.dumps(SPEC, indent=2) + "\n", encoding="utf-8")
    target = ROOT / "components" / "game" / "models" / "createHeadwearUpgradeModels.ts"
    target.write_text(SOURCE, encoding="utf-8")
    print(f"wrote {HERE / 'headwear-upgrade-spec.json'}")
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
