insert into public.trap_catalog(type,display_name,category,placement_radius,risk_weight,sort_order) values
('swinging_hammer','Swinging Hammer','sweeper',1.30,1.20,1),('rolling_fridge','Rolling Refrigerator','prop',1.10,1.45,2),('floor_fan','Floor Fan','movement',.90,.80,3),('soap_slick','Soap Slick','movement',.80,.70,4),('spring_pad','Spring Pad','movement',.75,.90,5),('angry_vacuum','Angry Vacuum','prop',1.20,1.55,6),('rotating_toilet','Rotating Toilet','sweeper',1.25,1.05,7),('giant_beach_ball','Giant Beach Ball','prop',.80,.60,8)
on conflict(type) do update set display_name=excluded.display_name,category=excluded.category,placement_radius=excluded.placement_radius,risk_weight=excluded.risk_weight,sort_order=excluded.sort_order;

insert into public.placement_zones(id,label,min_x,max_x,min_z,max_z,ground_y,max_occupants,allowed_types) values
('runway_front','Runway front',-2.3,2.3,6,7.5,.05,2,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),
('runway_mid','Runway middle',-2.3,2.3,7.8,9.2,.05,2,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),
('runway_back','Runway back',-2.3,2.3,9.5,10.7,.05,2,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),
('stones_front','First stones',-2.4,0,11.4,13,.1,1,array['floor_fan','soap_slick','spring_pad','giant_beach_ball']),('stones_mid','Middle stone',-1.2,1.2,13.2,14.8,.45,1,array['floor_fan','soap_slick','spring_pad','giant_beach_ball']),('stones_back','Last stone',0,2.5,15,16.4,.15,1,array['floor_fan','soap_slick','spring_pad','giant_beach_ball']),
('bridge_front','Bridge front',-1.05,1.05,17.5,19.1,.05,1,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),('bridge_mid','Bridge middle',-1.05,1.05,19.5,21.1,.05,1,array['swinging_hammer','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),('bridge_back','Bridge back',-1.05,1.05,21.5,23.4,.05,1,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),
('island_left','Left island',-2.75,-.7,25,29,.05,2,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),('island_right','Right island',.7,2.75,25,29,.05,2,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),('convergence','Convergence',-2.2,2.2,30.1,32,.05,2,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),
('ramp','Ramp',-1.55,1.55,32.8,34.6,.45,1,array['swinging_hammer','floor_fan','soap_slick','spring_pad','rotating_toilet','giant_beach_ball']),('finish_front','Finish approach',-2.6,2.6,35.4,37,.45,2,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball']),('finish_mid','Finish middle',-2.4,2.4,37.3,38.7,.45,1,array['swinging_hammer','rolling_fridge','floor_fan','soap_slick','spring_pad','angry_vacuum','rotating_toilet','giant_beach_ball'])
on conflict(id) do update set label=excluded.label,min_x=excluded.min_x,max_x=excluded.max_x,min_z=excluded.min_z,max_z=excluded.max_z,ground_y=excluded.ground_y,max_occupants=excluded.max_occupants,allowed_types=excluded.allowed_types;
