import { beforeAll, describe, expect, it } from "vitest";
import * as THREE from "three";
import {
  applyRunnerPose,
  buildRunnerForTest,
  captureRunnerRig,
  createRunnerGaitState,
  createRunnerPose,
  measureRunnerLimbs,
  updateRunnerPose,
  type RunnerLimbs,
  type RunnerPose,
  type RunnerPoseInput,
} from "@/components/game/PlayerVisual";
import { PLAYER } from "@/lib/game/constants";

/** The deck the runner stands on, in the rigid body's own frame. */
const DECK = -(PLAYER.capsuleHalfHeight + PLAYER.capsuleRadius);
const STEP = 1 / 60;

/**
 * The whole point of the cycle is that a foot carrying weight stays where the
 * player put it. Reading the pose object back would only prove the solver
 * agrees with itself, so every measurement here comes off the assembled model:
 * the rig is posed frame by frame and the shoes are then measured in world
 * space, exactly as they are drawn.
 */
interface Sample {
  time: number;
  /** Per foot: the lowest point of the sole, and where the ankle joint is. */
  soleY: [number, number];
  ankleZ: [number, number];
  toeZ: [number, number];
  pose: RunnerPose;
}

let model: THREE.Group;
let limbs: RunnerLimbs;

beforeAll(() => {
  model = buildRunnerForTest();
  const measured = measureRunnerLimbs(model);
  if (!measured) throw new Error("the sculpt no longer exposes the joints the cycle drives");
  limbs = measured;
});

function run(seconds: number, input: Omit<RunnerPoseInput, "elapsed">): Sample[] {
  const root = new THREE.Group();
  const instance = buildRunnerForTest();
  root.add(instance);
  const rig = captureRunnerRig(instance, root);
  // The shoe is two nodes: the upper on the ankle and the outsole hung beside
  // it off the leg. Measuring only the upper would miss the very failure this
  // file exists to catch, which is the two coming apart.
  const feet = shoes(instance);

  const state = createRunnerGaitState();
  const pose = createRunnerPose();
  const samples: Sample[] = [];
  const box = new THREE.Box3();
  const point = new THREE.Vector3();
  for (let time = 0; time < seconds; time += STEP) {
    updateRunnerPose(pose, state, { ...input, elapsed: time }, limbs, STEP);
    applyRunnerPose(rig, pose);
    root.updateMatrixWorld(true);
    const soleY: [number, number] = [0, 0];
    const ankleZ: [number, number] = [0, 0];
    const toeZ: [number, number] = [0, 0];
    for (const side of [0, 1] as const) {
      const [upper, outsole] = feet[side]!;
      box.setFromObject(upper);
      box.union(new THREE.Box3().setFromObject(outsole));
      soleY[side] = box.min.y;
      toeZ[side] = box.max.z;
      ankleZ[side] = point.setFromMatrixPosition(upper.matrixWorld).z;
    }
    samples.push({ time, soleY, ankleZ, toeZ, pose: structuredClone(pose) });
  }
  return samples;
}

function shoes(instance: THREE.Object3D): [THREE.Object3D, THREE.Object3D][] {
  return (["left", "right"] as const).map((side) => {
    const upper = instance.getObjectByName(`Sneaker ${side}__pivot`);
    const outsole = instance.getObjectByName(`Sole ${side}__pivot`);
    if (!upper || !outsole) throw new Error(`the sculpt no longer names the ${side} shoe`);
    return [upper, outsole] as [THREE.Object3D, THREE.Object3D];
  });
}

const walking: Omit<RunnerPoseInput, "elapsed"> = {
  speed: 2.4,
  verticalVelocity: 0,
  grounded: true,
  yaw: 0,
  stunned: false,
  pose: "playing",
  reducedMotion: false,
};

describe("the runner's feet stay on the deck they are drawn on", () => {
  it("measures its own leg off the sculpt instead of trusting a constant", () => {
    // Every length the gait solves against comes from here, and the sculpt is
    // regenerated by a pipeline this file does not own.
    expect(limbs.hipToAnkle).toBeGreaterThan(0.2);
    expect(limbs.hipToAnkle).toBeLessThan(1);
    expect(limbs.ankleToSole).toBeGreaterThan(0.05);
    expect(limbs.footToe).toBeGreaterThan(0.05);
    expect(limbs.footHeel).toBeGreaterThan(0.05);
    // The toe and heel levers cannot answer which way the shoe points: the
    // foot's Box3 is symmetric about the ankle, so footToe and footHeel come
    // out equal to the last decimal whichever way round it is mounted. They
    // did for the box this replaced too.
    expect(limbs.footToe).toBeCloseTo(limbs.footHeel, 3);
    // The sculpt stands its ankles forward of its hips rather than under them,
    // and treating the leg as a plumb line put the foot through the deck.
    expect(Math.abs(limbs.hipTilt)).toBeGreaterThan(0.01);
    expect(limbs.ankleRestAhead).toBeCloseTo(
      limbs.hipToAnkle * Math.sin(limbs.hipTilt),
      6,
    );
    // The two hips are mirrored about the centre line, whichever way round the
    // sculpt calls them.
    expect(limbs.hipSideX[0]).toBeCloseTo(-limbs.hipSideX[1], 6);
    expect(limbs.headAboveWaist).toBeGreaterThan(0.2);
  });

  it("points the shoe forward, low at the toe and tall at the collar", () => {
    // The bug this exists for: the sneaker mounted back to front, with the
    // ankle collar standing over the toes and the toe swell tapering out
    // behind the heel. Nothing else in this file noticed, because every extent
    // was correct - the envelope is symmetric, so footToe and footHeel are
    // equal either way round, and the sole still met the deck. Only the SHAPE
    // inside the envelope is asymmetric, so only the shape can be asked.
    //
    // A shoe is low where the toes are and tall where the ankle goes. Measured
    // in world space off the assembled model, front half against back half.
    const instance = buildRunnerForTest();
    instance.updateMatrixWorld(true);
    for (const side of ["left", "right"] as const) {
      const mesh = instance.getObjectByName(`Sneaker ${side}`);
      if (!(mesh instanceof THREE.Mesh)) throw new Error(`no ${side} sneaker mesh`);
      const position = mesh.geometry.getAttribute("position");
      const point = new THREE.Vector3();
      const whole = new THREE.Box3().setFromObject(mesh);
      const middle = (whole.min.z + whole.max.z) / 2;
      let front = -Infinity;
      let back = -Infinity;
      for (let i = 0; i < position.count; i += 1) {
        point.fromBufferAttribute(position, i).applyMatrix4(mesh.matrixWorld);
        if (point.z > middle) front = Math.max(front, point.y);
        else back = Math.max(back, point.y);
      }
      expect(
        back,
        `the ${side} shoe is mounted backwards: it stands ${front.toFixed(4)} high at `
          + `the front and only ${back.toFixed(4)} at the back, so the collar is over the toes`,
      ).toBeGreaterThan(front);
    }
  });

  it("never drives a foot through the deck at any speed", () => {
    for (const speed of [0, 0.8, 2.4, 4.6, 7.2]) {
      for (const sample of run(1.6, { ...walking, speed })) {
        const lowest = Math.min(sample.soleY[0], sample.soleY[1]);
        expect(
          lowest,
          `at ${speed}u/s a sole reached ${lowest.toFixed(4)}, below the ${DECK} deck`,
        ).toBeGreaterThan(DECK - 0.004);
      }
    }
  });

  it("keeps a foot on the deck through every frame of a walk", () => {
    // A walk has a duty factor above a half, so both stances overlap and the
    // runner is never unsupported. A frame where neither sole reaches the deck
    // is a frame where the whole body is floating.
    for (const sample of run(2, walking)) {
      const lowest = Math.min(sample.soleY[0], sample.soleY[1]);
      expect(lowest - DECK).toBeLessThan(0.006);
    }
  });

  it("holds the carrying foot still against the ground it is standing on", () => {
    // The visual moves with the body, so a planted foot travels backwards
    // through the body frame at exactly the speed the body travels forwards.
    // Adding the ground covered back on must leave it where it was.
    for (const speed of [1.2, 2.4, 4.6, 7.2]) {
      const samples = run(2, { ...walking, speed });
      let worst = 0;
      let checked = 0;
      for (let i = 1; i < samples.length; i += 1) {
        const previous = samples[i - 1]!;
        const current = samples[i]!;
        for (const side of [0, 1] as const) {
          const planted = previous.soleY[side] - DECK < 0.002
            && current.soleY[side] - DECK < 0.002;
          if (!planted) continue;
          const slide = current.ankleZ[side] - previous.ankleZ[side] + speed * STEP;
          worst = Math.max(worst, Math.abs(slide));
          checked += 1;
        }
      }
      expect(checked, `no planted frames were found at ${speed}u/s`).toBeGreaterThan(20);
      // Per frame the body covers speed * STEP. Anything the foot fails to hold
      // is skating, so bound the residual well under a tenth of that.
      expect(
        worst,
        `the planted foot slipped ${worst.toFixed(5)}u in one frame at ${speed}u/s, against `
          + `${(speed * STEP).toFixed(5)}u of ground covered`,
      ).toBeLessThan(speed * STEP * 0.08);
    }
  });

  it("plants both feet flat and still while standing", () => {
    const samples = run(3, { ...walking, speed: 0 });
    for (const sample of samples) {
      for (const side of [0, 1] as const) {
        expect(sample.soleY[side]).toBeCloseTo(DECK, 2);
      }
    }
    // Idle is not frozen - it breathes - but nothing about it may travel.
    const first = samples[0]!;
    const last = samples[samples.length - 1]!;
    expect(Math.abs(last.ankleZ[0] - first.ankleZ[0])).toBeLessThan(0.002);
    const chest = samples.map((sample) => sample.pose.chest);
    expect(Math.max(...chest) - Math.min(...chest)).toBeGreaterThan(0.004);
  });

  it("changes the shape of the stride with speed, not only its size", () => {
    // A walk keeps both feet down through part of the cycle; a run has a phase
    // with neither down. Scaling one curve by speed could never produce both.
    const overlap = (speed: number) => {
      const samples = run(2, { ...walking, speed });
      const both = samples.filter(
        (sample) => sample.soleY[0] - DECK < 0.002 && sample.soleY[1] - DECK < 0.002,
      );
      const neither = samples.filter(
        (sample) => sample.soleY[0] - DECK > 0.01 && sample.soleY[1] - DECK > 0.01,
      );
      return { both: both.length / samples.length, neither: neither.length / samples.length };
    };
    const walk = overlap(2);
    const sprint = overlap(7.2);
    expect(walk.both, "a walk should spend part of its cycle on both feet").toBeGreaterThan(0.05);
    expect(walk.neither, "a walk should never leave the deck").toBeLessThan(0.01);
    expect(sprint.neither, "a sprint should have a flight phase").toBeGreaterThan(0.1);
    expect(sprint.both, "a sprint should not double-support").toBeLessThan(0.02);
  });

  it("lands on the deck rather than through it", () => {
    const root = new THREE.Group();
    const instance = buildRunnerForTest();
    root.add(instance);
    const rig = captureRunnerRig(instance, root);
    const feet = shoes(instance);
    const state = createRunnerGaitState();
    const pose = createRunnerPose();
    const box = new THREE.Box3();
    let lowestAfterLanding = Infinity;
    let crouched = 0;
    for (let frame = 0; frame < 90; frame += 1) {
      const airborne = frame < 24;
      updateRunnerPose(
        pose,
        state,
        {
          ...walking,
          speed: 3,
          grounded: !airborne,
          verticalVelocity: airborne ? 7.4 - frame * 0.62 : 0,
          elapsed: frame * STEP,
        },
        limbs,
        STEP,
      );
      applyRunnerPose(rig, pose);
      root.updateMatrixWorld(true);
      if (airborne) continue;
      if (pose.lift < -0.02) crouched += 1;
      for (const [upper, outsole] of feet) {
        box.setFromObject(upper);
        box.union(new THREE.Box3().setFromObject(outsole));
        lowestAfterLanding = Math.min(lowestAfterLanding, box.min.y);
      }
    }
    expect(crouched, "landing should absorb into a crouch, not only a squash").toBeGreaterThan(4);
    expect(
      lowestAfterLanding,
      `the landing crouch pushed a sole to ${lowestAfterLanding.toFixed(4)}`,
    ).toBeGreaterThan(DECK - 0.004);
  });
});

describe("the runner answers the way it is steered", () => {
  it("turns the short way round through the heading seam", () => {
    // yaw arrives from atan2, so running across the back of the level crosses
    // +/-pi. Easing toward the raw difference spun the body most of a full turn.
    const state = createRunnerGaitState();
    const pose = createRunnerPose();
    const base = { ...walking, elapsed: 0 };
    updateRunnerPose(pose, state, { ...base, yaw: 3.1 }, limbs, STEP);
    const before = state.facing;
    for (let frame = 0; frame < 30; frame += 1) {
      updateRunnerPose(pose, state, { ...base, yaw: -3.1, elapsed: frame * STEP }, limbs, STEP);
    }
    const travelled = Math.abs(state.facing - before);
    expect(travelled, "the runner unwound the long way round the circle").toBeLessThan(Math.PI / 2);
  });

  it("banks into a turn and holds level when it is not turning", () => {
    const straight = run(1, walking);
    const turning: number[] = [];
    const state = createRunnerGaitState();
    const pose = createRunnerPose();
    for (let frame = 0; frame < 60; frame += 1) {
      updateRunnerPose(
        pose,
        state,
        { ...walking, speed: 6, yaw: frame * 0.035, elapsed: frame * STEP },
        limbs,
        STEP,
      );
      turning.push(pose.bodyRoll);
    }
    const straightRoll = Math.max(...straight.map((sample) => Math.abs(sample.pose.bodyRoll)));
    const turningRoll = Math.max(...turning.map(Math.abs));
    expect(turningRoll).toBeGreaterThan(straightRoll * 2);
  });

  it("keeps the cycle under reduced motion and drops the flourishes", () => {
    const plain = run(1.5, walking);
    const reduced = run(1.5, { ...walking, reducedMotion: true });
    const amplitude = (samples: Sample[], read: (pose: RunnerPose) => number) =>
      Math.max(...samples.map((sample) => Math.abs(read(sample.pose))));
    // Where the legs are is game information, so the stride is untouched.
    expect(amplitude(reduced, (pose) => pose.hipAngle[0])).toBeCloseTo(
      amplitude(plain, (pose) => pose.hipAngle[0]),
      6,
    );
    // The trunk's flourish against them is not.
    expect(amplitude(reduced, (pose) => pose.bodyTwist))
      .toBeLessThan(amplitude(plain, (pose) => pose.bodyTwist) * 0.5);
  });
});
